channels = {"bbc_one": {"name": "BBC One",
                        "images": {"sd": "bbc_one.png",
                                   "hd": "bbc_one_hd.png"},
                        "category": "Entertainment",
                        "sequence": 0},
            "bbc_two": {"name": "BBC Two",
                        "images": {"sd": "bbc_two.png",
                                   "hd": "bbc_two_hd.png"},
                        "category": "Entertainment",
                        "sequence": 1},
            "itv": {"name": "ITV",
                    "images": {"sd": "itv.png",
                               "hd": "itv_hd.png",
                               "sd_plus1": "itv_plus1.png"},
                    "category": "Entertainment",
                    "sequence": 2,
                    "sequence_plus1": 13},
            "channel_4": {"name": "Channel 4",
                          "images": {"sd": "channel_4.png",
                                     "hd": "channel_4_hd.png",
                                     "sd_plus1": "channel_4_plus1.png"},
                          "category": "Entertainment",
                          "sequence": 3,
                          "sequence_plus1": 4},
            "five": {"name": "Channel 5",
                     "images": {"sd": "channel_5.png",
                                "hd": "channel_5_hd.png",
                                "sd_plus1": "channel_5_plus1.png"},
                     "category": "Entertainment",
                     "sequence": 5,
                     "sequence_plus1": 6},
            "my5": {"name": "My 5",
                    "images": {"sd": "my5.png"},
                    "category": "Entertainment",
                    "sequence": 7},
            "bbc_four": {"name": "BBC Four",
                         "images": {"sd": "bbc_four.png",
                                    "hd": "bbc_four_hd.png"},
                         "category": "Entertainment",
                         "sequence": 8},
            "sky1": {"name": "Sky 1",
                     "images": {"sd": "sky1.png",
                                "hd": "sky1_hd.png"},
                     "category": "Entertainment",
                     "sequence": 9},
            "sky2": {"name": "Sky 2",
                     "images": {"sd": "sky2.png"},
                     "category": "Entertainment",
                     "sequence": 10},
            "sky_witness": {"name": "Sky Witness",
                            "images": {"sd": "sky_living.png",
                                       "hd": "sky_living_hd.png",
                                       "sd_plus1": "sky_living_plus1.png"},
                            "category": "Entertainment",
                            "sequence": 11,
                            "sequence_plus1": 12},
            "itv2": {"name": "ITV2",
                     "images": {"sd": "itv2.png",
                                      "hd": "itv2_plus1.png",
                                      "sd_plus1": "itv2_plus1.png"},
                     "category": "Entertainment",
                     "sequence": 14,
                     "sequence_plus1": 15},
            "itv3": {"name": "ITV3",
                     "images": {"sd": "itv3.png",
                                "hd": "itv3_hd.png",
                                "sd_plus1": "itv3_plus1.png"},
                     "category": "Entertainment",
                     "sequence": 16,
                     "sequence_plus1": 17},
            "itv4": {"name": "ITV4",
                     "images": {"sd": "itv4.png",
                                "hd": "itv4_hd.png",
                                "sd_plus1": "itv4_plus1.png"},
                     "category": "Entertainment",
                     "sequence": 18,
                     "sequence_plus1": 19},
            "itvbe": {"name": "ITVBe",
                      "images": {"sd": "itv_be.png",
                                 "sd_plus1": "itv_be_plus1.png"},
                      "category": "Entertainment",
                      "sequence": 20,
                      "sequence_plus1": 21},
            "sky_arts": {"name": "Sky Arts",
                         "images": {"sd": "sky_arts.png",
                                    "hd": "sky_arts_hd.png"},
                         "category": "Entertainment",
                         "sequence": 22},
            "pick": {"name": "Pick",
                     "images": {"sd": "pick.png"},
                     "category": "Entertainment",
                     "sequence": 23},
            "w": {"name": "W",
                  "images": {"sd": "w.png",
                             "hd": "w_hd.png",
                             "sd_plus": "w_plus1.png"},
                  "category": "Entertainment",
                  "sequence": 24,
                  "sequence_plus1": 25},
            "gold": {"name": "Gold",
                     "images": {"sd": "gold.png",
                                "sd_plus": "gold_plus1.png"},
                     "category": "Entertainment",
                     "sequence": 26,
                     "sequence_plus1": 27},
            "dave": {"name": "Dave",
                     "images": {"sd": "dave.png",
                                "hd": "dave_hd.png",
                                "sd_plus1": "dave_ja_vu.png"},
                     "category": "Entertainment",
                     "sequence": 28,
                     "sequence_plus1": 29},
            "alibi": {"name": "Alibi",
                      "images": {"sd": "alibi.png",
                                 "hd": "alibi_hd.png",
                                 "sd_plus1": "alibi_plus1.png"},
                      "category": "Entertainment",
                      "sequence": 30,
                      "sequence_plus1": 31},
            "comedy_central": {"name": "Comedy Central",
                               "images": {"sd": "comedy_central.png",
                                          "hd": "comedy_central_hd.png",
                                          "sd_plus1": "comedy_central_plus1.png"},
                               "category": "Entertainment",
                               "sequence": 32,
                               "sequence_plus1": 33},
            "comedy_central_extra": {"name": "Comedy Central Extra",
                                     "images": {"sd": "comedy_central_extra.png"},
                                     "category": "Entertainment",
                                     "sequence": 34},
            "mtv": {"name": "MTV",
                    "images": {"sd": "mtv.png",
                               "hd": "mtv_hd.png"},
                    "category": "Entertainment",
                    "sequence": 35},
            "syfy": {"name": "Syfy",
                     "images": {"sd": "syfy.png",
                                "hd": "syfy_hd.png",
                                "sd_plus1": "syfy_plus1.png"},
                     "category": "Entertainment",
                     "sequence": 36,
                     "sequence_plus1": 37},
            "universal_channel": {"name": "Universal Channel",
                                  "images": {"sd": "universal.png",
                                             "hd": "universal_hd.png",
                                             "sd_plus1": "universal_plus1.png"},
                                  "category": "Entertainment",
                                  "sequence": 38,
                                  "sequence_plus1": 39},
            "challenge": {"name": "Challenge",
                          "images": {"sd": "challenge.png",
                                     "sd_plus1": "challenge_plus1.png"},
                          "category": "Entertainment",
                          "sequence": 40,
                          "sequence_plus1": 41},
            "e4": {"name": "E4",
                   "images": {"sd": "e4.png",
                              "hd": "e4_hd.png",
                              "sd_plus1": "e4_plus1.png"},
                   "category": "Entertainment",
                   "sequence": 42,
                   "sequence_plus1": 43},
            "more4": {"name": "More4",
                      "images": {"sd": "more_4.png",
                                 "hd": "more_4_hd.png",
                                 "sd_plus1": "more_4_plus1.png"},
                      "category": "Entertainment",
                      "sequence": 44,
                      "sequence_plus1": 45},
            "cbs_reality": {"name": "CBS Reality",
                            "images": {"sd": "cbs_reality.png",
                                       "sd_plus1": "cbs_reality_plus1.png"},
                            "category": "Entertainment",
                            "sequence": 46,
                            "sequence_plus1": 47},
            "horror": {"name": "Horro",
                       "images": {"sd": "horror_channel.png",
                                  "sd_plus1": "horror_channel_plus1.png"},
                       "category": "Entertainment",
                       "sequence": 48,
                       "sequence_plus1": 49},
            "5*": {"name": "5*",
                   "images": {"sd": "5_star.png",
                              "sd_plus1": "5_star_plus1.png"},
                   "category": "Entertainment",
                   "sequence": 50,
                   "sequence_plus1": 51},
            "5usa": {"name": "5USA",
                     "images": {"sd": "5_usa.png",
                                "sd_plus1": "5_usa_plus1.png"},
                     "category": "Entertainment",
                     "sequence": 52,
                     "sequence_plus1": 53},
            "5select": {"name": "5SELECT",
                        "images": {"sd": "5_select.png"},
                        "category": "Entertainment",
                        "sequence": 54},
            "5spike": {"name": "5SPIKE",
                       "images": {"sd": "5_spike.png"},
                       "category": "Entertainment",
                       "sequence": 55},
            "paramount_network": {"name": "Paramount Network",
                                  "images": {"sd": "paramount_network.png",
                                             "hd": "paramount_network_hd.png"},
                                  "category": "Entertainment",
                                  "sequence": 56},
            "e!": {"name": "E!",
                   "images": {"sd": "e_entertainment.png"},
                   "category": "Entertainment",
                   "sequence": 57},
            "fox": {"name": "FOX",
                    "images": {"sd": "fox.png",
                               "hd": "fox_hd.png",
                               "sd_plus1": "fox_plus1.png"},
                    "category": "Entertainment",
                    "sequence": 58,
                    "sequence_plus1": 59},
            "made_in_leeds": {"name": "Made In Leeds",
                              "images": {"sd": "made_in_leeds.png"},
                              "category": "Entertainment",
                              "sequence": 60},
            "real_lives": {"name": "Real Lives",
                           "images": {"sd": "real_lives.png",
                                      "sd_plus1": "real_lives_plus1.png"},
                           "category": "Entertainment",
                           "sequence": 61,
                           "sequence_plus1": 62},
            "bbc_alba": {"name": "BBC Alba",
                         "images": {"sd": "bbc_alba.png"},
                         "category": "Entertainment",
                         "sequence": 63},
            "s4c": {"name": "S4C",
                    "images": {"sd": "s4c.png"},
                    "category": "Entertainment",
                    "sequence": 64},
            "tlc": {"name": "TLC",
                    "images": {"sd": "tlc.png",
                               "hd": "tlc_hd.png",
                               "sd_plus1": "tlc_plus1.png"},
                    "category": "Entertainment",
                    "sequence": 65,
                    "sequence_plus1": 66},
            "dmax": {"name": "DMAX",
                     "images": {"sd": "dmax.png",
                                "sd_plus1": "dmax_plus1.png"},
                     "category": "Entertainment",
                     "sequence": 67,
                     "sequence_plus1": 68},
            "quest": {"name": "Quest",
                      "images": {"sd": "quest.png",
                                 "sd_plus1": "quest_plus1.png"},
                      "category": "Entertainment",
                      "sequence": 69,
                      "sequence_plus1": 70},
            "bet": {"name": "BET",
                    "images": {"sd": "bet.png"},
                    "category": "Entertainment",
                    "sequence": 71},
            "true_entertainment": {"name": "True Entertainment",
                                   "images": {"sd": "true_entertainment.png"},
                                   "category": "Entertainment",
                                   "sequence": 72},
            "yourtv": {"name": "YourTV",
                       "images": {"sd": "yourtv.png"},
                       "category": "Entertainment",
                       "sequence": 73},
            "drama": {"name": "Drama",
                      "images": {"sd": "drama.png"},
                      "category": "Entertainment",
                      "sequence": 74},
            "cbs_action": {"name": "CBS Action",
                           "images": {"sd": "cbs_action.png"},
                           "category": "Entertainment",
                           "sequence": 75},
            "sony_crime": {"name": "Sony Crime",
                           "images": {"sd": "sony_tv.png"},
                           "category": "Entertainment",
                           "sequence": 76},
            "4seven": {"name": "4Seven",
                       "images": {"sd": "4seven.png"},
                       "category": "Entertainment",
                       "sequence": 77},
            "cbs_drama": {"name": "CBS Drama",
                          "images": {"sd": "cbs_drama.png"},
                          "category": "Entertainment",
                          "sequence": 78},
            "tru_tv": {"name": "TruTV",
                       "images": {"sd": "tru_tv.png"},
                       "category": "Entertainment",
                       "sequence": 79},
            "sky_cinema_premiere": {"name": "Sky Cinema Premiere",
                                    "images": {"sd": "sky_cinema_premiere.png",
                                               "hd": "sky_cinema_premiere_hd.png",
                                               "sd_plus1": "sky_cinema_premiere_plus1.png"},
                                    "category": "Movies",
                                    "sequence": 100,
                                    "sequence_plus1": 101},
            "sky_cinema_hits": {"name": "Sky Cinema Hits",
                                "images": {"sd": "sky_cinema_hits.png",
                                           "hd": "sky_cinema_hits_hd.png"},
                                "category": "Movies",
                                "sequence": 102},
            "sky_cinema_greats": {"name": "Sky Cinema Greats",
                                  "images": {"sd": "sky_cinema_greats.png",
                                             "hd": "sky_cinema_greats_hd.png"},
                                  "category": "Movies",
                                  "sequence": 103},
            "sky_cinema_disney": {"name": "Sky Cinema Disney",
                                  "images": {"sd": "sky_cinema_disney.png",
                                             "hd": "sky_cinema_disney_hd.png"},
                                  "category": "Movies",
                                  "sequence": 104},
            "sky_cinema_family": {"name": "Sky Cinema Family",
                                  "images": {"sd": "sky_cinema_drama.png",
                                             "hd": "sky_cinema_drama_hd.png"},
                                  "category": "Movies",
                                  "sequence": 105},
            "sky_cinema_action": {"name": "Sky Cinema Action",
                                  "images": {"sd": "sky_cinema_action.png",
                                             "hd": "sky_cinema_action_hd.png"},
                                  "category": "Movies",
                                  "sequence": 106},
            "sky_cinema_comedy": {"name": "Sky Cinema Comedy",
                                  "images": {"sd": "sky_cinema_comedy.png",
                                             "hd": "sky_cinema_comedy_hd.png"},
                                  "category": "Movies",
                                  "sequence": 107},
            "sky_cinema_thriller": {"name": "Sky Cinema Thriller",
                                    "images": {"sd": "sky_cinema_thriller.png",
                                               "hd": "sky_cinema_thriller_hd.png"},
                                    "category": "Movies",
                                    "sequence": 108},
            "sky_cinema_drama": {"name": "Sky Cinema Drama",
                                 "images": {"sd": "sky_cinema_drama.png",
                                            "hd": "sky_cinema_drama_hd.png"},
                                 "category": "Movies",
                                 "sequence": 109},
            "sky_cinema_sci_fi_&_horror": {"name": "Sky Cinema Sci Fi & Horror",
                                           "images": {"sd": "sky_cinema_scifi.png",
                                                      "hd": "sky_cinema_scifi_hd.png"},
                                           "category": "Movies",
                                           "sequence": 110},
            "sky_cinema_select": {"name": "Sky Cinema Select",
                                  "images": {"sd": "sky_cinema_select.png",
                                             "hd": "sky_cinema_select_hd.png"},
                                  "category": "Movies",
                                  "sequence": 111},
            "tcm": {"name": "TCM",
                    "images": {"sd": "tcm.png",
                               "hd": "tcm_hd.png",
                               "sd_plus": "tcm_plus1.png"},
                    "category": "Movies",
                    "sequence": 112,
                    "sequence_plus": 113},
            "movies24": {"name": "Movies 24",
                         "images": {"sd": "movies_24.png",
                                    "sd_plus": "movies_24_plus1.png"},
                         "category": "Movies",
                         "sequence": 114,
                         "sequence_plus": 115},
            "true_movies": {"name": "True Movies",
                            "images": {"sd": "true_movies.png"},
                            "category": "Movies",
                            "sequence": 116},
            "sony_movie_channel": {"name": "Sony Movie Channel",
                                   "images": {"sd": "sony_movie_channel.png"},
                                   "category": "Movies",
                                   "sequence": 117},
            "movies4men": {"name": "Movies4Men",
                                   "images": {"sd": "movies4men.png"},
                                   "category": "Movies",
                                   "sequence": 118},
            "film4": {"name": "Film4",
                      "images": {"sd": "film4.png",
                                 "hd": "film4_hd.png",
                                 "sd_plus": "film4_plus1.png"},
                      "category": "Movies",
                      "sequence": 119,
                      "sequence_plus": 120},
            "sky_sports_news": {"name": "Sky Sports News",
                                "images": {"sd": "sky_sports_news.png",
                                           "hd": "sky_sports_news_hd.png"},
                                "category": "Sports",
                                "sequence": 200},
            "sky_sports_mix": {"name": "Sky Sports Mix",
                               "images": {"sd": "sky_sports_mix.png",
                                          "hd": "sky_sports_mix_hd.png"},
                               "category": "Sports",
                               "sequence": 201},
            "sky_sports_main_event": {"name": "Sky Sports Main Event",
                                      "images": {"sd": "sky_sports_main_event.png",
                                                 "hd": "sky_sports_main_event_hd.png"},
                                      "category": "Sports",
                                      "sequence": 202},
            "sky_sports_premier_league": {"name": "Sky Sports Premier League",
                                          "images": {"sd": "sky_sports_premier_league.png",
                                                     "hd": "sky_sports_premier_league_hd.png"},
                                          "category": "Sports",
                                          "sequence": 203},
            "sky_sports_football": {"name": "Sky Sports Football",
                                    "images": {"sd": "sky_sports_football.png",
                                               "hd": "sky_sports_football_hd.png"},
                                    "category": "Sports",
                                    "sequence": 204},
            "sky_sports_cricket": {"name": "Sky Sports Cricket",
                                   "images": {"sd": "sky_sports_cricket.png",
                                              "hd": "sky_sports_cricket_hd.png"},
                                   "category": "Sports",
                                   "sequence": 205},
            "sky_sports_golf": {"name": "Sky Sports Golf",
                                "images": {"sd": "sky_sports_golf.png",
                                           "hd": "sky_sports_golf_hd.png"},
                                "category": "Sports",
                                "sequence": 206},
            "sky_sports_f1": {"name": "Sky Sports F1",
                              "images": {"sd": "sky_sports_f1.png",
                                         "hd": "sky_sports_f1_hd.png"},
                              "category": "Sports",
                              "sequence": 207},
            "sky_sports_action": {"name": "Sky Sports Action",
                                  "images": {"sd": "sky_sports_action.png",
                                             "hd": "sky_sports_action_hd.png"},
                                  "category": "Sports",
                                  "sequence": 208},
            "sky_sports_arena": {"name": "Sky Sports Arena",
                                 "images": {"sd": "sky_sports_arena.png",
                                            "hd": "sky_sports_arena_hd.png"},
                                 "category": "Sports",
                                 "sequence": 209},
            "at_the_races": {"name": "At the Races",
                             "images": {"sd": "at_the_races.png"},
                             "category": "Sports",
                             "sequence": 210},
            "bt_sport_1": {"name": "BT Sports 1",
                           "images": {"sd": "bt_sport_1.png",
                                      "hd": "bt_sport_1_hd.png"},
                           "category": "Sports",
                           "sequence": 211},
            "bt_sport_2": {"name": "BT Sports 2",
                           "images": {"sd": "bt_sport_2.png",
                                      "hd": "bt_sport_2_hd.png"},
                           "category": "Sports",
                           "sequence": 212},
            "bt_sport_3": {"name": "BT Sports 3",
                           "images": {"sd": "bt_sport_3.png",
                                      "hd": "bt_sport_3_hd.png"},
                           "category": "Sports",
                           "sequence": 213},
            "bt_sport_espn": {"name": "BT Sport ESPN",
                              "images": {"sd": "bt_sport_espn.png",
                                         "hd": "bt_sport_espn_hd.png"},
                              "category": "Sports",
                              "sequence": 214},
            "eurosport1": {"name": "Eurosport 1",
                           "images": {"sd": "eurosport1.png",
                                      "hd": "eurosport1_hd.png"},
                           "category": "Sports",
                           "sequence": 215},
            "eurosport2": {"name": "Eurosport 2",
                           "images": {"sd": "eurosport2.png",
                                      "hd": "eurosport2_hd.png"},
                           "category": "Sports",
                           "sequence": 216},
            "motorsport_tv": {"name": "Motorsport TV",
                              "images": {"sd": "motorsport_tv.png"},
                              "category": "Sports",
                              "sequence": 217},
            "permier_sports": {"name": "Premier Sports",
                               "images": {"sd": "permier_sports.png"},
                               "category": "Sports",
                               "sequence": 218},
            "permier_sports2": {"name": "Permier Sports 2",
                                "images": {"sd": "permier_sports2.png"},
                                "category": "Sports",
                                "sequence": 219},
            "free_sports": {"name": "Free Sports",
                            "images": {"sd": "free_sports.png"},
                            "category": "Sports",
                            "sequence": 220},
            "yesterday": {"name": "Yesterday",
                          "images": {"sd": "yesterday.png",
                                     "sd_plus1": "yesterday_plus1.png"},
                          "category": "Factual",
                          "sequence": 300,
                          "sequence_plus": 301},
            "eden": {"name": "Eden",
                     "images": {"sd": "eden.png",
                                "hd": "eden_hd.png",
                                "sd_plus1": "eden_plus1.png"},
                     "category": "Factual",
                     "sequence": 302,
                     "sequence_plus": 303},
            "discovery_channel": {"name": "Discovery Channel",
                                  "images": {"sd": "discovery_channel.png",
                                             "hd": "discovery_channel_hd.png",
                                             "sd_plus1": "discovery_channel_plus1.png"},
                                  "category": "Factual",
                                  "sequence": 304,
                                  "sequence_plus1": 305},
            "investigation_discovery": {"name": "Investigation Discovery",
                                        "images": {"sd": "investigation_discovery.png",
                                                   "sd_plus1": "investigation_discovery_plus1.png"},
                                        "category": "Factual",
                                        "sequence": 306,
                                        "sequence_plus1": 307},
            "animal_planet": {"name": "Animal Planet",
                              "images": {"sd": "animal_planet.png",
                                         "hd": "animal_planet_hd.png",
                                         "sd_plus1": "animal_planet_plus1.png"},
                              "category": "Factual",
                              "sequence": 308,
                              "sequence_plus1": 309},
            "discovery_science": {"name": "Discovery Science",
                                  "images": {"sd": "discovery_science.png",
                                             "sd_plus1": "discovery_science_plus1.png"},
                                  "category": "Factual",
                                  "sequence": 310,
                                  "sequence_plus1": 311},
            "discovery_turbo": {"name": "Discovery Turbo",
                                "images": {"sd": "discovery_turbo.png"},
                                "category": "Factual",
                                "sequence": 312},
            "discovery_history": {"name": "Discovery History",
                                  "images": {"sd": "discovery_history.png",
                                             "sd_plus1": "discovery_history_plus1.png"},
                                  "category": "Factual",
                                  "sequence": 313,
                                  "sequence_plus1": 314},
            "nat_geo_wild": {"name": "Nat Geo Wild",
                             "images": {"sd": "nat_geo_wild.png",
                                        "hd": "nat_geo_wild_hd.png"},
                             "category": "Factual",
                             "sequence": 315},
            "national_geographic": {"name": "National Geographic",
                                    "images": {"sd": "national_geographic.png",
                                               "hd": "national_geographic_hd.png",
                                               "sd_plus1": "national_geographic_plus1.png"},
                                    "category": "Factual",
                                    "sequence": 316,
                                    "sequence_plus1": 317},
            "love_nature": {"name": "Love Nature",
                            "images": {"sd": "love_nature.png"},
                            "category": "Factual",
                            "sequence": 318},
            "horse_and_country": {"name": "Horse & Country",
                                  "images": {"sd": "horse_and_country.png"},
                                  "category": "Factual",
                                  "sequence": 319},
            "community_channel": {"name": "Community Channel",
                                  "images": {"sd": "community_channel.png"},
                                  "category": "Factual",
                                  "sequence": 320},
            "history": {"name": "History",
                        "images": {"sd": "history.png",
                                   "sd_plus1": "history_plus1.png"},
                        "category": "Factual",
                        "sequence": 321,
                        "sequence_plus1": 322},
            "h2": {"name": "H2",
                   "images": {"sd": "h2.png",
                              "hd": "h2_hd.png"},
                   "category": "Factual",
                   "sequence": 323},
            "lifetime": {"name": "Lifetime",
                         "images": {"sd": "lifetime.png",
                                    "hd": "lifetime_hd.png"},
                         "category": "Factual",
                         "sequence": 324},
            "crime_and_investigation": {"name": "Crime and Investigation",
                                        "images": {"sd": "crime_and_investigation.png"},
                                        "category": "Factual",
                                        "sequence": 325},
            "pbs_america": {"name": "PBS America",
                            "images": {"sd": "pbs_america.png"},
                            "category": "Factual",
                            "sequence": 326},
            "forces_tv": {"name": "Forces TV",
                          "images": {"sd": "forces_tv.png"},
                          "category": "Factual",
                          "sequence": 327},
            "good_food": {"name": "Good Food",
                          "images": {"sd": "good_food.png",
                                     "hd": "good_food_hd.png",
                                     "sd_plus1": "good_food_plus1.png"},
                          "category": "Lifestyle",
                          "sequence": 400,
                          "sequence_plus1": 401},
            "food_network": {"name": "Food Network",
                             "images": {"sd": "food_network.png"},
                             "category": "Lifestyle",
                             "sequence": 402},
            "home": {"name": "Home",
                     "images": {"sd": "home.png",
                                "sd_plus1": "home_plus1.png"},
                     "category": "Lifestyle",
                     "sequence": 403,
                     "sequence_plus1": 404},
            "really": {"name": "Really",
                       "images": {"sd": "really.png"},
                       "category": "Lifestyle",
                       "sequence": 405},
            "discovery_home_and_health": {"name": "Discovery Home and Health",
                                          "images": {"sd": "discovery_home_and_health.png",
                                                     "sd_plus1": "discovery_home_and_health_plus1.png"},
                                          "category": "Lifestyle",
                                          "sequence": 406,
                                          "sequence_plus1": 407},
            "discovery_shed": {"name": "Discovery Shed",
                               "images": {"sd": "discovery_shed.png"},
                               "category": "Lifestyle",
                               "sequence": 408},
            "ginx": {"name": "GINX Esport TV",
                     "images": {"sd": "ginx.png"},
                     "category": "Lifestyle",
                     "sequence": 409},
            "travel_channel": {"name": "Travel Channel",
                               "images": {"sd": "travel_channel.png"},
                               "category": "Lifestyle",
                               "sequence": 410},
            "cbbc": {"name": "CBBC",
                     "images": {"sd": "cbbc.png",
                                "hd": "cbbc_hd.png"},
                     "category": "Kids",
                     "sequence": 500},
            "cbeebies": {"name": "Cbeebies",
                         "images": {"sd": "cbeebies.png",
                                    "hd": "cbeebies_hd.png"},
                         "category": "Kids",
                         "sequence": 501},
            "cartoon_network": {"name": "Cartoon Network",
                                "images": {"sd": "cartoon_network.png",
                                           "hd": "cartoon_network_hd.png",
                                           "sd_plus1": "cartoon_network_plus1.png"},
                                "category": "Kids",
                                "sequence": 502,
                                "sequence_plus1": 503},
            "cartoonito": {"name": "Cartoonito",
                           "images": {"sd": "cartoonito.png"},
                           "category": "Kids",
                           "sequence": 504},
            "disney_xd": {"name": "Disney XD",
                          "images": {"sd": "disney_xd.png",
                                     "sd_plus1": "disney_xd_plus1.png"},
                          "category": "Kids",
                          "sequence": 505,
                          "sequence_plus1": 506},
            "nickelodeon": {"name": "Nickelodeon",
                            "images": {"sd": "nickelodeon.png",
                                       "hd": "nickelodeon_hd.png",
                                       "sd_plus1": "nickelodeon_plus1.png"},
                            "category": "Kids",
                            "sequence": 507,
                            "sequence_plus1": 508},
            "nick_junior": {"name": "Nick Junior",
                            "images": {"sd": "nick_junior.png"},
                            "category": "Kids",
                            "sequence": 509},
            "nick_junior_too": {"name": "Nick Junior Too",
                                "images": {"sd": "nick_junior_too.png"},
                                "category": "Kids",
                                "sequence": 510},
            "nick_toons": {"name": "Nick Toons",
                           "images": {"sd": "nick_toons.png"},
                           "category": "Kids",
                           "sequence": 511},
            "disney_channel": {"name": "Disney Channel",
                               "images": {"sd": "disney_channel.png",
                                          "sd_plus1": "disney_channel_plus1.png"},
                               "category": "Kids",
                               "sequence": 512,
                               "sequence_plus1": 513},
            "disney_junior": {"name": "Disney Junior",
                              "images": {"sd": "disney_junior.png"},
                              "category": "Kids",
                              "sequence": 514},
            "boomerang": {"name": "Boomerang",
                          "images": {"sd": "boomerang.png",
                                     "sd_plus1": "boomerang_plus1.png"},
                          "category": "Kids",
                          "sequence": 515,
                          "sequence_plus1": 516},
            "citv": {"name": "CITV",
                     "images": {"sd": "citv.png"},
                     "category": "Kids",
                     "sequence": 517},
            "pop": {"name": "Pop",
                    "images": {"sd": "pop.png"},
                    "category": "Kids",
                    "sequence": 518},
            "tiny_pop": {"name": "Tiny Pop",
                         "images": {"sd": "tiny_pop.png"},
                         "category": "Kids",
                         "sequence": 519},
            "mtv_music": {"name": "MTV Music",
                          "images": {"sd": "mtv_music.png"},
                          "category": "Music",
                          "sequence": 600},
            "mtv_live_hd": {"name": "MTV Live HD",
                            "images": {"hd": "mtv_live_hd.png"},
                            "category": "Music",
                            "sequence": 601},
            "mtv_hits": {"name": "MTV Hits",
                         "images": {"sd": "mtv_hits.png"},
                         "category": "Music",
                         "sequence": 602},
            "mtv_base": {"name": "MTV base",
                         "images": {"sd": "mtv_base.png"},
                         "category": "Music",
                         "sequence": 603},
            "mtv_dance": {"name": "MTV Dance",
                          "images": {"sd": "mtv_dance.png"},
                          "category": "Music",
                          "sequence": 604},
            "mtv_rocks": {"name": "MTV Rocks",
                          "images": {"sd": "mtv_rocks.png"},
                          "category": "Music",
                          "sequence": 605},
            "vh1": {"name": "VH1",
                    "images": {"sd": "vh1.png"},
                    "category": "Music",
                    "sequence": 606},
            "mtv_omg": {"name": "MTV_OMG",
                     "images": {"sd": "mtv_omg.png"},
                     "category": "Music",
                     "sequence": 607},
            "4music": {"name": "4 Music",
                       "images": {"sd": "4music.png"},
                       "category": "Music",
                       "sequence": 608},
            "the_box": {"name": "The Box",
                        "images": {"sd": "the_box.png"},
                        "category": "Music",
                        "sequence": 609},
            "kiss": {"name": "Kiss",
                     "images": {"sd": "kiss.png"},
                     "category": "Music",
                     "sequence": 610},
            "box_hits": {"name": "Box Hits",
                         "images": {"sd": "box_hits.png"},
                         "category": "Music",
                         "sequence": 611},
            "box_upfront": {"name": "Box Upfront",
                            "images": {"sd": "box_upfront.png"},
                            "category": "Music",
                            "sequence": 612},
            "magic": {"name": "Magic",
                      "images": {"sd": "magic.png"},
                      "category": "Music",
                      "sequence": 613},
            "kerrang_tv": {"name": "Kerrang! TV",
                           "images": {"sd": "kerrang.png"},
                           "category": "Music",
                           "sequence": 614},
            "clubland": {"name": "Clubland",
                         "images": {"sd": "clubland.png"},
                         "category": "Music",
                         "sequence": 616},
            "bbc_news": {"name": "BBC News",
                         "images": {"sd": "bbc_news.png",
                                    "hd": "bbc_news_hd.png"},
                         "category": "News",
                         "sequence": 700},
            "sky_news": {"name": "Sky News",
                         "images": {"sd": "sky_news.png",
                                    "hd": "sky_news_hd.png"},
                         "category": "News",
                         "sequence": 701},
            "bbc_parliament": {"name": "BBC Parliament",
                               "images": {"sd": "bbc_parliament.png"},
                               "category": "News",
                               "sequence": 702},
            "cnn": {"name": "CNN",
                    "images": {"sd": "cnn.png"},
                    "category": "News",
                    "sequence": 703},
            "bloomberg": {"name": "Bloomberg",
                          "images": {"sd": "bloomberg.png"},
                          "category": "News",
                          "sequence": 704},
            "cnbc": {"name": "CNBX",
                     "images": {"sd": "cnbc.png"},
                     "category": "News",
                     "sequence": 705},
            "euronews": {"name": "Euronews",
                         "images": {"sd": "euronews.png"},
                         "category": "News",
                         "sequence": 706},
            "ndtv24x7": {"name": "NDTV 24x7",
                         "images": {"sd": "ndtv_24x7.png"},
                         "category": "News",
                         "sequence": 707},
            "bbc_radio_1": {"name": "BBC Radio 1",
                            "images": {"sd": "bbc_radio_1.png"},
                            "category": "Radio",
                            "sequence": 800},
            "bbc_radio_1_xtra": {"name": "BBC Radio 1 Xtra",
                                 "images": {"sd": "bbc_radio_1_xtra.png"},
                                 "category": "Radio",
                                 "sequence": 801},
            "bbc_radio_2": {"name": "BBC Radio 2",
                            "images": {"sd": "bbc_radio_2.png"},
                            "category": "Radio",
                            "sequence": 802},
            "bbc_radio_3": {"name": "BBC Radio 3",
                            "images": {"sd": "bbc_radio_3.png"},
                            "category": "Radio",
                            "sequence": 803},
            "bbc_radio_4_fm": {"name": "BBC Radio 4 FM",
                               "images": {"sd": "bbc_radio_4fm.png"},
                               "category": "Radio",
                               "sequence": 804},
            "bbc_radio_4_extra": {"name": "BBC Radio 4 Extra",
                                  "images": {"sd": "bbc_radio_4_extra.png"},
                                  "category": "Radio",
                                  "sequence": 805},
            "bbc_radio_4_long_wave": {"name": "BBC Radio 4 Long Wave",
                                      "images": {"sd": "bbc_radio_4_long_wave.png"},
                                      "category": "Radio",
                                      "sequence": 806},
            "bbc_radio_5_live": {"name": "BBC Radio 5 Live",
                                 "images": {"sd": "bbc_radio_5live.png"},
                                 "category": "Radio",
                                 "sequence": 807},
            "bbc_radio_5_live_sports_extra": {"name": "BBC Radio 5 Live Sports Extra",
                                              "images": {"sd": "bbc_radio_5live_sports_extra.png"},
                                              "category": "Radio",
                                              "sequence": 808},
            "bbc_radio_6_music": {"name": "BBC Radio 6 Music",
                                  "images": {"sd": "bbc_radio_6music.png"},
                                  "category": "Radio",
                                  "sequence": 809},
            "bbc_world_service": {"name": "BBC World Service",
                                  "images": {"sd": "bbc_world_service.png"},
                                  "category": "Radio",
                                  "sequence": 810},
            "absolute_radio": {"name": "Absolute Radio",
                               "images": {"sd": "absolute_radio.png"},
                               "category": "Radio",
                               "sequence": 811},
            "smooth_radio": {"name": "Smooth Radio",
                             "images": {"sd": "smooth_radio.png"},
                             "category": "Radio",
                             "sequence": 812},
            "heart_fm": {"name": "Heart FM",
                         "images": {"sd": "heart_fm.png"},
                         "category": "Radio",
                         "sequence": 813},
            "lbc": {"name": "LBC",
                    "images": {"sd": "lbc_radio.png"},
                    "category": "Radio",
                    "sequence": 814},
            "classic_fm": {"name": "Classic FM",
                           "images": {"sd": "classic_fm.png"},
                           "category": "Radio",
                           "sequence": 815},
            "gold_radio": {"name": "Gold Radio",
                           "images": {"sd": "gold_radio.png"},
                           "category": "Radio",
                           "sequence": 816},
            "planet_rock": {"name": "Planet Rock",
                            "images": {"sd": "planet_rock.png"},
                            "category": "Radio",
                            "sequence": 817},
            "magic_radio": {"name": "Magic Radio",
                            "images": {"sd": "magic_radio.png"},
                            "category": "Radio",
                            "sequence": 818},
            "absolute80s": {"name": "Absolute 80s",
                            "images": {"sd": "absolute_80s.png"},
                            "category": "Radio",
                            "sequence": 819},
            "absolute_classic_rock": {"name": "Absolute Classic Rock",
                                      "images": {"sd": "absolute_classic_rock.png"},
                                      "category": "Radio",
                                      "sequence": 820},
            "capital_fm": {"name": "Capital FM",
                           "images": {"sd": "capital_fm.png"},
                           "category": "Radio",
                           "sequence": 821},
            "capital_xtra": {"name": "Capital Xtra",
                             "images": {"sd": "capital_xtra.png"},
                             "category": "Radio",
                             "sequence": 822},
            "radio_x": {"name": "Radio X",
                        "images": {"sd": "radio_x.png"},
                        "category": "Radio",
                        "sequence": 823},
            "kiss_fm": {"name": "Kiss FM",
                        "images": {"sd": "kiss_fm.png"},
                        "category": "Radio",
                        "sequence": 824},
            "talksport": {"name": "talkSPORT",
                          "images": {"sd": "talksport.png"},
                          "category": "Radio",
                          "sequence": 825}
            }
