channels = {"BBC ONE": {"sd": {"image": "bbc_one.png"},
                        "hd": {"image": "bbc_one_hd.png"},
                        "category": "Entertainment",
                        "sequence": 0},
            "BBC TWO": {"sd": {"image": "bbc_two.png"},
                        "hd": {"image": "bbc_two_hd.png"},
                        "category": "Entertainment",
                        "sequence": 1},
            "ITV": {"sd": {"image": "itv.png"},
                    "hd": {"image": "itv_hd.png"},
                    "category": "Entertainment",
                    "sequence": 2},
            "Channel 4": {"sd": {"image": "channel_4.png"},
                          "hd": {"image": "channel_4_hd.png"},
                          "category": "Entertainment",
                          "sequence": 3},
            "Channel 4 +1": {"sd": {"image": "channel_4_plus1.png"},
                             "hd": False,
                             "category": "Entertainment",
                             "sequence": 4},
            "Channel 5": {"sd": {"image": "channel_5.png"},
                          "hd": {"image": "channel_5_hd.png"},
                          "category": "Entertainment",
                          "sequence": 5},
            "Channel 5 +1": {"sd": {"image": "channel_5_plus1.png"},
                             "hd": False,
                             "category": "Entertainment",
                             "sequence": 6},
            "My5": {"sd": {"image": "my5.png"},
                    "hd": False,
                    "category": "Entertainment",
                    "sequence": 7},
            "BBC FOUR": {"sd": {"image": "bbc_four.png"},
                         "hd": {"image": "bbc_four_hd.png"},
                         "category": "Entertainment",
                         "sequence": 8},
            "Sky1": {"sd": {"image": "sky1.png"},
                     "hd": {"image": "sky1_hd.png"},
                     "category": "Entertainment",
                     "sequence": 9},
            "Sky2": {"sd": {"image": "sky2.png"},
                     "hd": False,
                     "category": "Entertainment",
                     "sequence": 10},
            "Sky Living": {"sd": {"image": "sky_living.png"},
                           "hd": {"image": "sky_living_hd.png"},
                           "category": "Entertainment",
                           "sequence": 11},
            "Sky Living +1": {"sd": {"image": "sky_living_plus1.png"},
                              "hd": False,
                              "category": "Entertainment",
                              "sequence": 12},
            "ITV +1": {"sd": {"image": "itv_plus1.png"},
                       "hd": False,
                       "category": "Entertainment",
                       "sequence": 13},
            "ITV2": {"sd": {"image": "itv2.png"},
                     "hd": {"image": "itv2_plus1.png"},
                     "category": "Entertainment",
                     "sequence": 14},
            "ITV2 +1": {"sd": {"image": "itv2_plus1.png"},
                        "hd": False,
                        "category": "Entertainment",
                        "sequence": 15},
            "ITV3": {"sd": {"image": "itv3.png"},
                     "hd": {"image": "itv3_hd.png"},
                     "category": "Entertainment",
                     "sequence": 16},
            "ITV3 +1": {"sd": {"image": "itv3_plus1.png"},
                        "hd": False,
                        "category": "Entertainment",
                        "sequence": 17},
            "ITV4": {"sd": {"image": "itv4.png"},
                     "hd": {"image": "itv4_hd.png"},
                     "category": "Entertainment",
                     "sequence": 18},
            "ITV4 +1": {"sd": {"image": "itv4_plus1.png"},
                        "hd": False,
                        "category": "Entertainment",
                        "sequence": 19},
            "ITVBe": {"sd": {"image": "itv_be.png"},
                      "hd": False,
                      "category": "Entertainment",
                      "sequence": 20},
            "ITVBe +1": {"sd": {"image": "itv_be_plus1.png"},
                         "hd": False,
                         "category": "Entertainment",
                         "sequence": 21},
            "Sky Arts": {"sd": {"image": "sky_arts.png"},
                         "hd": {"image": "sky_arts_hd.png"},
                         "category": "Entertainment",
                         "sequence": 22},
            "Pick": {"sd": {"image": "pick.png"},
                     "hd": False,
                     "category": "Entertainment",
                     "sequence": 23},
            "W": {"sd": {"image": "w.png"},
                  "hd": {"image": "w_hd.png"},
                  "category": "Entertainment",
                  "sequence": 24},
            "W +1": {"sd": {"image": "w_plus1.png"},
                     "hd": False,
                     "category": "Entertainment",
                     "sequence": 25},
            "Gold": {"sd": {"image": "gold.png"},
                     "hd": False,
                     "category": "Entertainment",
                     "sequence": 26},
            "Gold +1": {"sd": {"image": "gold_plus1.png"},
                        "hd": False,
                        "category": "Entertainment",
                        "sequence": 27},
            "Dave": {"sd": {"image": "dave.png"},
                     "hd": {"image": "dave_hd.png"},
                     "category": "Entertainment",
                     "sequence": 28},
            "Dave ja vu": {"sd": {"image": "dave_ja_vu.png"},
                           "hd": False,
                           "category": "Entertainment",
                           "sequence": 29},
            "Alibi": {"sd": {"image": "alibi.png"},
                      "hd": {"image": "alibi_hd.png"},
                      "category": "Entertainment",
                      "sequence": 30},
            "Alibi +1": {"sd": {"image": "alibi_plus1.png"},
                         "hd": False,
                         "category": "Entertainment",
                         "sequence": 31},
            "Comedy Central": {"sd": {"image": "comedy_central.png"},
                               "hd": {"image": "comedy_central_hd.png"},
                               "category": "Entertainment",
                               "sequence": 32},
            "Comedy Central +1": {"sd": {"image": "comedy_central_plus1.png"},
                                  "hd": False,
                                  "category": "Entertainment",
                                  "sequence": 33},
            "Comedy Central Extra": {"sd": {"image": "comedy_central_extra.png"},
                                     "hd": False,
                                     "category": "Entertainment",
                                     "sequence": 34},
            "MTV": {"sd": {"image": "mtv.png"},
                    "hd": {"image": "mtv_hd.png"},
                    "category": "Entertainment",
                    "sequence": 35},
            "syfy": {"sd": {"image": "syfy.png"},
                     "hd": {"image": "syfy_hd.png"},
                     "category": "Entertainment",
                     "sequence": 36},
            "syfy +1": {"sd": {"image": "syfy_plus1.png"},
                        "hd": False,
                        "category": "Entertainment",
                        "sequence": 37},
            "Universal Channel": {"sd": {"image": "universal.png"},
                                  "hd": {"image": "universal_hd.png"},
                                  "category": "Entertainment",
                                  "sequence": 38},
            "Universal Channel +1": {"sd": {"image": "universal_plus1.png"},
                                     "hd": False,
                                     "category": "Entertainment",
                                     "sequence": 39},
            "Challenge": {"sd": {"image": "challenge.png"},
                          "hd": False,
                          "category": "Entertainment",
                          "sequence": 40},
            "Challenge +1": {"sd": {"image": "challenge_plus1.png"},
                             "hd": False,
                             "category": "Entertainment",
                             "sequence": 41},
            "E4": {"sd": {"image": "e4.png"},
                   "hd": {"image": "e4_hd.png"},
                   "category": "Entertainment",
                   "sequence": 42},
            "E4 +1": {"sd": {"image": "e4_plus1.png"},
                      "hd": False,
                      "category": "Entertainment",
                      "sequence": 43},
            "More4": {"sd": {"image": "more_4.png"},
                      "hd": {"image": "more_4_hd.png"},
                      "category": "Entertainment",
                      "sequence": 44},
            "More4 +1": {"sd": {"image": "more_4_plus1.png"},
                         "hd": False,
                         "category": "Entertainment",
                         "sequence": 45},
            "CBS Reality": {"sd": {"image": "cbs_reality.png"},
                            "hd": False,
                            "category": "Entertainment",
                            "sequence": 46},
            "CBS Reality +1": {"sd": {"image": "cbs_reality_plus1.png"},
                               "hd": False,
                               "category": "Entertainment",
                               "sequence": 47},
            "Horror Channel": {"sd": {"image": "horror_channel.png"},
                               "hd": False,
                               "category": "Entertainment",
                               "sequence": 48},
            "Horror Channel +1": {"sd": {"image": "horror_channel_plus1.png"},
                                  "hd": False,
                                  "category": "Entertainment",
                                  "sequence": 49},
            "5*": {"sd": {"image": "5_star.png"},
                   "hd": False,
                   "category": "Entertainment",
                   "sequence": 50},
            "5* +1": {"sd": {"image": "5_star_plus1.png"},
                      "hd": False,
                      "category": "Entertainment",
                      "sequence": 51},
            "5 USA": {"sd": {"image": "5_usa.png"},
                      "hd": False,
                      "category": "Entertainment",
                      "sequence": 52},
            "5 USA +1": {"sd": {"image": "5_usa_plus1.png"},
                         "hd": False,
                         "category": "Entertainment",
                         "sequence": 53},
            "5 Spike": {"sd": {"image": "5_spike.png"},
                        "hd": False,
                        "category": "Entertainment",
                        "sequence": 54},
            "E! Entertainment": {"sd": {"image": "e_entertainment.png"},
                                 "hd": False,
                                 "category": "Entertainment",
                                 "sequence": 55},
            "FOX": {"sd": {"image": "fox.png"},
                    "hd": {"image": "fox_hd.png"},
                    "category": "Entertainment",
                    "sequence": 56},
            "FOX +1": {"sd": {"image": "fox_plus1.png"},
                       "hd": False,
                       "category": "Entertainment",
                       "sequence": 57},
            "Made in Leeds": {"sd": {"image": "made_in_leeds.png"},
                              "hd": False,
                              "category": "Entertainment",
                              "sequence": 58},
            "Real Lives": {"sd": {"image": "real_lives.png"},
                           "hd": False,
                           "category": "Entertainment",
                           "sequence": 59},
            "Real Lives +1": {"sd": {"image": "real_lives_plus1.png"},
                              "hd": False,
                              "category": "Entertainment",
                              "sequence": 60},
            "BBC ALBA": {"sd": {"image": "bbc_alba.png"},
                         "hd": False,
                         "category": "Entertainment",
                         "sequence": 61},
            "S4C": {"sd": {"image": "s4c.png"},
                    "hd": False,
                    "category": "Entertainment",
                    "sequence": 62},
            "TLC": {"sd": {"image": "tlc.png"},
                    "hd": {"image": "tlc_hd.png"},
                    "category": "Entertainment",
                    "sequence": 63},
            "TLC +1": {"sd": {"image": "tlc_plus1.png"},
                       "hd": False,
                       "category": "Entertainment",
                       "sequence": 64},
            "DMAX": {"sd": {"image": "dmax.png"},
                     "hd": False,
                     "category": "Entertainment",
                     "sequence": 65},
            "DMAX +1": {"sd": {"image": "dmax_plus1.png"},
                        "hd": False,
                        "category": "Entertainment",
                        "sequence": 66},
            "Quest": {"sd": {"image": "quest.png"},
                      "hd": False,
                      "category": "Entertainment",
                      "sequence": 67},
            "Quest +1": {"sd": {"image": "quest_plus1.png"},
                         "hd": False,
                         "category": "Entertainment",
                         "sequence": 68},
            "BET": {"sd": {"image": "bet.png"},
                    "hd": False,
                    "category": "Entertainment",
                    "sequence": 69},
            "True Entertainment": {"sd": {"image": "true_entertainment.png"},
                                   "hd": False,
                                   "category": "Entertainment",
                                   "sequence": 70},
            "Drama": {"sd": {"image": "drama.png"},
                      "hd": False,
                      "category": "Entertainment",
                      "sequence": 71},
            "CBS Action": {"sd": {"image": "cbs_action.png"},
                           "hd": False,
                           "category": "Entertainment",
                           "sequence": 72},
            "Sony TV": {"sd": {"image": "sony_tv.png"},
                        "hd": False,
                        "category": "Entertainment",
                        "sequence": 73},
            "4Seven": {"sd": {"image": "4seven.png"},
                       "hd": False,
                       "category": "Entertainment",
                       "sequence": 74},
            "CBS Drama": {"sd": {"image": "cbs_drama.png"},
                          "hd": False,
                          "category": "Entertainment",
                          "sequence": 75},
            "TruTV": {"sd": {"image": "tru_tv.png"},
                      "hd": False,
                      "category": "Entertainment",
                      "sequence": 76},
            "Sky Cinema Premiere": {"sd": {"image": "sky_cinema_premiere.png"},
                                    "hd": {"image": "sky_cinema_premiere_hd.png"},
                                    "category": "Movies",
                                    "sequence": 100},
            "Sky Cinema Premiere +1": {"sd": {"image": "sky_cinema_premiere_plus1.png"},
                                       "hd": False,
                                       "category": "Movies",
                                       "sequence": 101},
            "Sky Cinema Hits": {"sd": {"image": "sky_cinema_hits.png"},
                                "hd": {"image": "sky_cinema_hits_hd.png"},
                                "category": "Movies",
                                "sequence": 102},
            "Sky Cinema Greats": {"sd": {"image": "sky_cinema_greats.png"},
                                  "hd": {"image": "sky_cinema_greats_hd.png"},
                                  "category": "Movies",
                                  "sequence": 103},
            "Sky Cinema Disney": {"sd": {"image": "sky_cinema_disney.png"},
                                  "hd": {"image": "sky_cinema_disney_hd.png"},
                                  "category": "Movies",
                                  "sequence": 104},
            "Sky Cinema Family": {"sd": {"image": "sky_cinema_drama.png"},
                                  "hd": {"image": "sky_cinema_drama_hd.png"},
                                  "category": "Movies",
                                  "sequence": 105},
            "Sky Cinema Action": {"sd": {"image": "sky_cinema_action.png"},
                                  "hd": {"image": "sky_cinema_action_hd.png"},
                                  "category": "Movies",
                                  "sequence": 106},
            "Sky Cinema Comedy": {"sd": {"image": "sky_cinema_comedy.png"},
                                  "hd": {"image": "sky_cinema_comedy_hd.png"},
                                  "category": "Movies",
                                  "sequence": 107},
            "Sky Cinema Thriller": {"sd": {"image": "sky_cinema_thriller.png"},
                                    "hd": {"image": "sky_cinema_thriller_hd.png"},
                                    "category": "Movies",
                                    "sequence": 108},
            "Sky Cinema Drama": {"sd": {"image": "sky_cinema_drama.png"},
                                 "hd": {"image": "sky_cinema_drama_hd.png"},
                                 "category": "Movies",
                                 "sequence": 109},
            "Sky Cinema Sci Fi & Horror": {"sd": {"image": "sky_cinema_scifi.png"},
                                           "hd": {"image": "sky_cinema_scifi_hd.png"},
                                           "category": "Movies",
                                           "sequence": 110},
            "Sky Cinema Select": {"sd": {"image": "sky_cinema_select.png"},
                                  "hd": {"image": "sky_cinema_select_hd.png"},
                                  "category": "Movies",
                                  "sequence": 111},
            "TCM": {"sd": {"image": "tcm.png"},
                    "hd": {"image": "tcm_hd.png"},
                    "category": "Movies",
                    "sequence": 112},
            "TCM +1": {"sd": {"image": "tcm_plus1.png"},
                       "hd": False,
                       "category": "Movies",
                       "sequence": 113},
            "Movies 24": {"sd": {"image": "movies_24.png"},
                          "hd": False,
                          "category": "Movies",
                          "sequence": 114},
            "Movies 24 +1": {"sd": {"image": "movies_24_plus1.png"},
                             "hd": False,
                             "category": "Movies",
                             "sequence": 115},
            "True Movies": {"sd": {"image": "true_movies.png"},
                            "hd": False,
                            "category": "Movies",
                            "sequence": 116},
            "Sony Movie Channel": {"sd": {"image": "sony_movie_channel.png"},
                                   "hd": False,
                                   "category": "Movies",
                                   "sequence": 117},
            "Film4": {"sd": {"image": "film4.png"},
                      "hd": {"image": "film4_hd.png"},
                      "category": "Movies",
                      "sequence": 118},
            "Film4 +1": {"sd": {"image": "film4_plus1.png"},
                         "hd": False,
                         "category": "Movies",
                         "sequence": 119},
            "Sky Sports News": {"sd": {"image": "sky_sports_news.png"},
                                "hd": {"image": "sky_sports_news_hd.png"},
                                "category": "Sports",
                                "sequence": 200},
            "Sky Sports Mix": {"sd": {"image": "sky_sports_mix.png"},
                               "hd": {"image": "sky_sports_mix_hd.png"},
                               "category": "Sports",
                               "sequence": 201},
            "Sky Sports Main Event": {"sd": {"image": "sky_sports_main_event.png"},
                                      "hd": {"image": "sky_sports_main_event_hd.png"},
                                      "category": "Sports",
                                      "sequence": 202},
            "Sky Sports Premier League": {"sd": {"image": "sky_sports_premier_league.png"},
                                          "hd": {"image": "sky_sports_premier_league_hd.png"},
                                          "category": "Sports",
                                          "sequence": 203},
            "Sky Sports Football": {"sd": {"image": "sky_sports_football.png"},
                                    "hd": {"image": "sky_sports_football_hd.png"},
                                    "category": "Sports",
                                    "sequence": 204},
            "Sky Sports Cricket": {"sd": {"image": "sky_sports_cricket.png"},
                                   "hd": {"image": "sky_sports_cricket_hd.png"},
                                   "category": "Sports",
                                   "sequence": 205},
            "Sky Sports Golf": {"sd": {"image": "sky_sports_golf.png"},
                                "hd": {"image": "sky_sports_golf_hd.png"},
                                "category": "Sports",
                                "sequence": 206},
            "Sky Sports F1": {"sd": {"image": "sky_sports_f1.png"},
                              "hd": {"image": "sky_sports_f1_hd.png"},
                              "category": "Sports",
                              "sequence": 207},
            "Sky Sports Action": {"sd": {"image": "sky_sports_action.png"},
                                  "hd": {"image": "sky_sports_action_hd.png"},
                                  "category": "Sports",
                                  "sequence": 208},
            "Sky Sports Arena": {"sd": {"image": "sky_sports_arena.png"},
                                 "hd": {"image": "sky_sports_arena_hd.png"},
                                 "category": "Sports",
                                 "sequence": 209},
            "At The Races": {"sd": {"image": "at_the_races.png"},
                             "hd": False,
                             "category": "Sports",
                             "sequence": 210},
            "BT Sport 1": {"sd": {"image": "bt_sport_1.png"},
                           "hd": {"image": "bt_sport_1_hd.png"},
                           "category": "Sports",
                           "sequence": 211},
            "BT Sport 2": {"sd": {"image": "bt_sport_2.png"},
                           "hd": {"image": "bt_sport_2_hd.png"},
                           "category": "Sports",
                           "sequence": 212},
            "BT Sport 3": {"sd": {"image": "bt_sport_3.png"},
                           "hd": {"image": "bt_sport_3_hd.png"},
                           "category": "Sports",
                           "sequence": 213},
            "BT Sport ESPN": {"sd": {"image": "bt_sport_espn.png"},
                              "hd": {"image": "bt_sport_espn_hd.png"},
                              "category": "Sports",
                              "sequence": 214},
            "Eurosport 1": {"sd": {"image": "eurosport1.png"},
                            "hd": {"image": "eurosport1_hd.png"},
                            "category": "Sports",
                            "sequence": 215},
            "Eurosport 2": {"sd": {"image": "eurosport2.png"},
                            "hd": {"image": "eurosport2_hd.png"},
                            "category": "Sports",
                            "sequence": 216},
            "Motorsport TV": {"sd": {"image": "motorsport_tv.png"},
                              "hd": False,
                              "category": "Sports",
                              "sequence": 217},
            "FIA Formula E": {"sd": {"image": "fia_formula_e.png"},
                              "hd": False,
                              "category": "Sports",
                              "sequence": 218},
            "BIKE": {"sd": {"image": "bike.png"},
                     "hd": False,
                     "category": "Sports",
                     "sequence": 219},
            "COPA90": {"sd": {"image": "copa90.png"},
                       "hd": False,
                       "category": "Sports",
                       "sequence": 220},
            "Yesterday": {"sd": {"image": "yesterday.png"},
                          "hd": False,
                          "category": "Factual",
                          "sequence": 300},
            "Yesterday +1": {"sd": {"image": "yesterday_plus1.png"},
                             "hd": False,
                             "category": "Factual",
                             "sequence": 301},
            "Eden": {"sd": {"image": "eden.png"},
                     "hd": {"image": "eden_hd.png"},
                     "category": "Factual",
                     "sequence": 302},
            "Eden +1": {"sd": {"image": "eden_plus1.png"},
                        "hd": False,
                        "category": "Factual",
                        "sequence": 303},
            "Discovery Channel": {"sd": {"image": "discovery_channel.png"},
                                  "hd": {"image": "discovery_channel_hd.png"},
                                  "category": "Factual",
                                  "sequence": 304},
            "Discovery Channel +1": {"sd": {"image": "discovery_channel_plus1.png"},
                                     "hd": False,
                                     "category": "Factual",
                                     "sequence": 305},
            "Investigation Discovery": {"sd": {"image": "investigation_discovery.png"},
                                        "hd": False,
                                        "category": "Factual",
                                        "sequence": 306},
            "Investigation Discovery +1": {"sd": {"image": "investigation_discovery_plus1.png"},
                                           "hd": False,
                                           "category": "Factual",
                                           "sequence": 307},
            "Animal Planet": {"sd": {"image": "animal_planet.png"},
                              "hd": {"image": "animal_planet_hd.png"},
                              "category": "Factual",
                              "sequence": 308},
            "Animal Planet +1": {"sd": {"image": "animal_planet_plus1.png"},
                                 "hd": False,
                                 "category": "Factual",
                                 "sequence": 309},
            "Discovery Science": {"sd": {"image": "discovery_science.png"},
                                  "hd": False,
                                  "category": "Factual",
                                  "sequence": 310},
            "Discovery Science +1": {"sd": {"image": "discovery_science_plus1.png"},
                                     "hd": False,
                                     "category": "Factual",
                                     "sequence": 311},
            "Discovery Turbo": {"sd": {"image": "discovery_turbo.png"},
                                "hd": False,
                                "category": "Factual",
                                "sequence": 312},
            "Discovery History": {"sd": {"image": "discovery_history.png"},
                                  "hd": False,
                                  "category": "Factual",
                                  "sequence": 313},
            "Discovery History +1": {"sd": {"image": "discovery_history_plus1.png"},
                                     "hd": False,
                                     "category": "Factual",
                                     "sequence": 314},
            "Nat Geo Wild": {"sd": {"image": "nat_geo_wild.png"},
                             "hd": {"image": "nat_geo_wild_hd.png"},
                             "category": "Factual",
                             "sequence": 315},
            "National Geographic": {"sd": {"image": "national_geographic.png"},
                                    "hd": {"image": "national_geographic_hd.png"},
                                    "category": "Factual",
                                    "sequence": 316},
            "National Geographic +1": {"sd": {"image": "national_geographic_plus1.png"},
                                       "hd": False,
                                       "category": "Factual",
                                       "sequence": 317},
            "Community Channel": {"sd": {"image": "community_channel.png"},
                                  "hd": False,
                                  "category": "Factual",
                                  "sequence": 318},
            "History": {"sd": {"image": "history.png"},
                        "hd": False,
                        "category": "Factual",
                        "sequence": 319},
            "History +1": {"sd": {"image": "history_plus1.png"},
                           "hd": False,
                           "category": "Factual",
                           "sequence": 320},
            "H2": {"sd": {"image": "h2.png"},
                   "hd": {"image": "h2_hd.png"},
                   "category": "Factual",
                   "sequence": 321},
            "Lifetime": {"sd": {"image": "lifetime.png"},
                         "hd": {"image": "lifetime_hd.png"},
                         "category": "Factual",
                         "sequence": 322},
            "Crime and Investigation": {"sd": {"image": "crime_and_investigation.png"},
                                        "hd": False,
                                        "category": "Factual",
                                        "sequence": 323},
            "PBS America": {"sd": {"image": "pbs_america.png"},
                            "hd": False,
                            "category": "Factual",
                            "sequence": 324},
            "Forces TV": {"sd": {"image": "forces_tv.png"},
                          "hd": False,
                          "category": "Factual",
                          "sequence": 325},
            "Good Food": {"sd": {"image": "good_food.png"},
                          "hd": {"image": "good_food_hd.png"},
                          "category": "Lifestyle",
                          "sequence": 400},
            "Good Food +1": {"sd": {"image": "good_food_plus1.png"},
                             "hd": False,
                             "category": "Lifestyle",
                             "sequence": 401},
            "Food Network": {"sd": {"image": "food_network.png"},
                             "hd": False,
                             "category": "Lifestyle",
                             "sequence": 402},
            "Home": {"sd": {"image": "home.png"},
                     "hd": False,
                     "category": "Lifestyle",
                     "sequence": 403},
            "Home +1": {"sd": {"image": "home_plus1.png"},
                        "hd": False,
                        "category": "Lifestyle",
                        "sequence": 404},
            "Really": {"sd": {"image": "really.png"},
                       "hd": False,
                       "category": "Lifestyle",
                       "sequence": 405},
            "Discovery Home & Health": {"sd": {"image": "discovery_home_and_health.png"},
                                        "hd": False,
                                        "category": "Lifestyle",
                                        "sequence": 406},
            "Discovery Home & Health +1": {"sd": {"image": "discovery_home_and_health_plus1.png"},
                                           "hd": False,
                                           "category": "Lifestyle",
                                           "sequence": 407},
            "Discovery Shed": {"sd": {"image": "discovery_shed.png"},
                               "hd": False,
                               "category": "Lifestyle",
                               "sequence": 408},
            "Ginx Esports TV": {"sd": {"image": "ginx.png"},
                                "hd": False,
                                "category": "Lifestyle",
                                "sequence": 409},
            "Travel Channel": {"sd": {"image": "travel_channel.png"},
                               "hd": False,
                               "category": "Lifestyle",
                               "sequence": 410},
            "CBBC": {"sd": {"image": "cbbc.png"},
                     "hd": {"image": "cbbc_hd.png"},
                     "category": "Kids",
                     "sequence": 500},
            "Cbeebies": {"sd": {"image": "cbeebies.png"},
                         "hd": {"image": "cbeebies_hd.png"},
                         "category": "Kids",
                         "sequence": 501},
            "Cartoon Network": {"sd": {"image": "cartoon_network.png"},
                                "hd": {"image": "cartoon_network_hd.png"},
                                "category": "Kids",
                                "sequence": 502},
            "Cartoon Network +1": {"sd": {"image": "cartoon_network_plus1.png"},
                                   "hd": False,
                                   "category": "Kids",
                                   "sequence": 503},
            "Cartoonito": {"sd": {"image": "cartoonito.png"},
                           "hd": False,
                           "category": "Kids",
                           "sequence": 504},
            "Disney XD": {"sd": {"image": "disney_xd.png"},
                          "hd": False,
                          "category": "Kids",
                          "sequence": 505},
            "Disney XD +1": {"sd": {"image": "disney_xd_plus1.png"},
                             "hd": False,
                             "category": "Kids",
                             "sequence": 506},
            "Nickelodeon": {"sd": {"image": "nickelodeon.png"},
                            "hd": {"image": "nickelodeon_hd.png"},
                            "category": "Kids",
                            "sequence": 507},
            "Nickelodeon +1": {"sd": {"image": "nickelodeon_plus1.png"},
                               "hd": False,
                               "category": "Kids",
                               "sequence": 508},
            "Nick Junior": {"sd": {"image": "nick_junior.png"},
                            "hd": False,
                            "category": "Kids",
                            "sequence": 509},
            "Nick Junior Too": {"sd": {"image": "nick_junior_too.png"},
                                "hd": False,
                                "category": "Kids",
                                "sequence": 510},
            "Nick Toons": {"sd": {"image": "nick_toons.png"},
                           "hd": False,
                           "category": "Kids",
                           "sequence": 511},
            "Disney Channel": {"sd": {"image": "disney_channel.png"},
                               "hd": False,
                               "category": "Kids",
                               "sequence": 512},
            "Disney Channel +1": {"sd": {"image": "disney_channel_plus1.png"},
                                  "hd": False,
                                  "category": "Kids",
                                  "sequence": 513},
            "Disney Junior": {"sd": {"image": "disney_junior.png"},
                              "hd": False,
                              "category": "Kids",
                              "sequence": 514},
            "Boomerang": {"sd": {"image": "boomerang.png"},
                          "hd": False,
                          "category": "Kids",
                          "sequence": 515},
            "Boomerang +1": {"sd": {"image": "boomerang_plus1.png"},
                             "hd": False,
                             "category": "Kids",
                             "sequence": 516},
            "CITV": {"sd": {"image": "citv.png"},
                     "hd": False,
                     "category": "Kids",
                     "sequence": 517},
            "Pop": {"sd": {"image": "pop.png"},
                    "hd": False,
                    "category": "Kids",
                    "sequence": 518},
            "Tiny Pop": {"sd": {"image": "tiny_pop.png"},
                         "hd": False,
                         "category": "Kids",
                         "sequence": 519},
            "MTV Music": {"sd": {"image": "mtv_music.png"},
                          "hd": False,
                          "category": "Music",
                          "sequence": 600},
            "MTV Live HD": {"sd": False,
                            "hd": {"image": "mtv_live_hd.png"},
                            "category": "Music",
                            "sequence": 601},
            "MTV Hits": {"sd": {"image": "mtv_hits.png"},
                         "hd": False,
                         "category": "Music",
                         "sequence": 602},
            "MTV Base": {"sd": {"image": "mtv_base.png"},
                         "hd": False,
                         "category": "Music",
                         "sequence": 603},
            "MTV Dance": {"sd": {"image": "mtv_dance.png"},
                          "hd": False,
                          "category": "Music",
                          "sequence": 604},
            "MTV Rocks": {"sd": {"image": "mtv_rocks.png"},
                          "hd": False,
                          "category": "Music",
                          "sequence": 605},
            "VH1": {"sd": {"image": "vh1.png"},
                    "hd": False,
                    "category": "Music",
                    "sequence": 606},
            "Viva": {"sd": {"image": "viva.png"},
                     "hd": False,
                     "category": "Music",
                     "sequence": 607},
            "4 Music": {"sd": {"image": "4music.png"},
                        "hd": False,
                        "category": "Music",
                        "sequence": 608},
            "The Box": {"sd": {"image": "the_box.png"},
                        "hd": False,
                        "category": "Music",
                        "sequence": 609},
            "Kiss": {"sd": {"image": "kiss.png"},
                     "hd": False,
                     "category": "Music",
                     "sequence": 610},
            "Box Hits": {"sd": {"image": "box_hits.png"},
                         "hd": False,
                         "category": "Music",
                         "sequence": 611},
            "Box Upfront": {"sd": {"image": "box_upfront.png"},
                            "hd": False,
                            "category": "Music",
                            "sequence": 612},
            "Magic": {"sd": {"image": "magic.png"},
                      "hd": False,
                      "category": "Music",
                      "sequence": 613},
            "Kerrang! TV": {"sd": {"image": "kerrang.png"},
                            "hd": False,
                            "category": "Music",
                            "sequence": 614},
            "Vintage TV": {"sd": {"image": "vintage_tv.png"},
                           "hd": False,
                           "category": "Music",
                           "sequence": 615},
            "Clubland": {"sd": {"image": "clubland.png"},
                         "hd": False,
                         "category": "Music",
                         "sequence": 616},
            "BBC News": {"sd": {"image": "bbc_news.png"},
                         "hd": {"image": "bbc_news_hd.png"},
                         "category": "News",
                         "sequence": 700},
            "Sky News": {"sd": {"image": "sky_news.png"},
                         "hd": {"image": "sky_news_hd.png"},
                         "category": "News",
                         "sequence": 701},
            "BBC Parliament": {"sd": {"image": "bbc_parliament.png"},
                               "hd": False,
                               "category": "News",
                               "sequence": 702},
            "CNN": {"sd": {"image": "cnn.png"},
                    "hd": False,
                    "category": "News",
                    "sequence": 703},
            "Bloomberg": {"sd": {"image": "bloomberg.png"},
                          "hd": False,
                          "category": "News",
                          "sequence": 704},
            "CNBC": {"sd": {"image": "cnbc.png"},
                     "hd": False,
                     "category": "News",
                     "sequence": 705},
            "Euronews": {"sd": {"image": "euronews.png"},
                         "hd": False,
                         "category": "News",
                         "sequence": 706},
            "NDTV 24x7": {"sd": {"image": "ndtv_24x7.png"},
                          "hd": False,
                          "category": "News",
                          "sequence": 707},
            "BBC Radio 1": {"sd": {"image": "bbc_radio_1.png"},
                            "hd": False,
                            "category": "Radio",
                            "sequence": 800},
            "BBC Radio 1 Xtra": {"sd": {"image": "bbc_radio_1_xtra.png"},
                                 "hd": False,
                                 "category": "Radio",
                                 "sequence": 801},
            "BBC Radio 2": {"sd": {"image": "bbc_radio_2.png"},
                            "hd": False,
                            "category": "Radio",
                            "sequence": 802},
            "BBC Radio 3": {"sd": {"image": "bbc_radio_3.png"},
                            "hd": False,
                            "category": "Radio",
                            "sequence": 803},
            "BBC Radio 4 FM": {"sd": {"image": "bbc_radio_4fm.png"},
                               "hd": False,
                               "category": "Radio",
                               "sequence": 804},
            "BBC Radio 4 Extra": {"sd": {"image": "bbc_radio_4_extra.png"},
                                  "hd": False,
                                  "category": "Radio",
                                  "sequence": 805},
            "BBC Radio 4 Long Wave": {"sd": {"image": "bbc_radio_4_long_wave.png"},
                                      "hd": False,
                                      "category": "Radio",
                                      "sequence": 806},
            "BBC Radio 5 Live": {"sd": {"image": "bbc_radio_5live.png"},
                                 "hd": False,
                                 "category": "Radio",
                                 "sequence": 807},
            "BBC Radio 5 Live Sports Extra": {"sd": {"image": "bbc_radio_5live_sports_extra.png"},
                                              "hd": False,
                                              "category": "Radio",
                                              "sequence": 808},
            "BBC Radio 6 Music": {"sd": {"image": "bbc_radio_6music.png"},
                                  "hd": False,
                                  "category": "Radio",
                                  "sequence": 809},
            "BBC World Service": {"sd": {"image": "bbc_world_service.png"},
                                  "hd": False,
                                  "category": "Radio",
                                  "sequence": 810},
            "Absolute Radio": {"sd": {"image": "absolute_radio.png"},
                               "hd": False,
                               "category": "Radio",
                               "sequence": 811},
            "Smooth Radio": {"sd": {"image": "smooth_radio.png"},
                             "hd": False,
                             "category": "Radio",
                             "sequence": 812},
            "Heart FM": {"sd": {"image": "heart_fm.png"},
                         "hd": False,
                         "category": "Radio",
                         "sequence": 813},
            "LBC": {"sd": {"image": "lbc_radio.png"},
                    "hd": False,
                    "category": "Radio",
                    "sequence": 814},
            "Classic FM": {"sd": {"image": "classic_fm.png"},
                           "hd": False,
                           "category": "Radio",
                           "sequence": 815},
            "Gold Radio": {"sd": {"image": "gold_radio.png"},
                           "hd": False,
                           "category": "Radio",
                           "sequence": 816},
            "Planet Rock": {"sd": {"image": "planet_rock.png"},
                            "hd": False,
                            "category": "Radio",
                            "sequence": 817},
            "Magic Radio": {"sd": {"image": "magic_radio.png"},
                            "hd": False,
                            "category": "Radio",
                            "sequence": 818},
            "Absolute 80s": {"sd": {"image": "absolute_80s.png"},
                             "hd": False,
                             "category": "Radio",
                             "sequence": 819},
            "Absolute Classic Rock": {"sd": {"image": "absolute_classic_rock.png"},
                                      "hd": False,
                                      "category": "Radio",
                                      "sequence": 820},
            "Capital FM": {"sd": {"image": "capital_fm.png"},
                           "hd": False,
                           "category": "Radio",
                           "sequence": 821},
            "Capital Xtra": {"sd": {"image": "capital_xtra.png"},
                             "hd": False,
                             "category": "Radio",
                             "sequence": 822},
            "Radio X": {"sd": {"image": "radio_x.png"},
                        "hd": False,
                        "category": "Radio",
                        "sequence": 823},
            "Kiss FM": {"sd": {"image": "kiss_fm.png"},
                        "hd": False,
                        "category": "Radio",
                        "sequence": 824},
            "talkSPORT": {"sd": {"image": "talksport.png"},
                          "hd": False,
                          "category": "Radio",
                          "sequence": 825}
            }
