channels = {"BBC ONE": {"images": {"sd": "bbc_one.png",
                                   "hd": "bbc_one_hd.png"},
                        "category": "Entertainment",
                        "sequence": 0},
            "BBC TWO": {"images": {"sd": "bbc_two.png",
                                   "hd": "bbc_two_hd.png"},
                        "category": "Entertainment",
                        "sequence": 1},
            "ITV": {"images": {"sd": "itv.png",
                               "hd": "itv_hd.png",
                               "sd_plus1": "itv_plus1.png"},
                    "category": "Entertainment",
                    "sequence": 2,
                    "sequence_plus1": 13},
            "Channel 4": {"images": {"sd": "channel_4.png",
                                     "hd": "channel_4_hd.png",
                                     "sd_plus1": "channel_4_plus1.png"},
                          "category": "Entertainment",
                          "sequence": 3,
                          "sequence_plus1": 4},
            "Channel 5": {"images": {"sd": "channel_5.png",
                                     "hd": "channel_5_hd.png",
                                     "sd_plus1": "channel_5_plus1.png"},
                          "category": "Entertainment",
                          "sequence": 5,
                          "sequence_plus1": 6},
            "My5": {"images": {"sd": "my5.png"},
                    "category": "Entertainment",
                    "sequence": 7},
            "BBC FOUR": {"images": {"sd": "bbc_four.png",
                                    "hd": "bbc_four_hd.png"},
                         "category": "Entertainment",
                         "sequence": 8},
            "Sky1": {"images": {"sd": "sky1.png",
                                "hd": "sky1_hd.png"},
                     "category": "Entertainment",
                     "sequence": 9},
            "Sky2": {"images": {"sd": "sky2.png"},
                     "category": "Entertainment",
                     "sequence": 10},
            "Sky Living": {"images": {"sd": "sky_living.png",
                                      "hd": "sky_living_hd.png",
                                      "sd_plus1": "sky_living_plus1.png"},
                           "category": "Entertainment",
                           "sequence": 11,
                           "sequence_plus1": 12},
            "ITV2": {"images": {"sd": "itv2.png",
                                      "hd": "itv2_plus1.png",
                                      "sd_plus1": "itv2_plus1.png"},
                     "category": "Entertainment",
                     "sequence": 14,
                     "sequence_plus1": 15},
            "ITV3": {"images": {"sd": "itv3.png",
                                "hd": "itv3_hd.png",
                                "sd_plus1": "itv3_plus1.png"},
                     "category": "Entertainment",
                     "sequence": 16,
                     "sequence_plus1": 17},
            "ITV4": {"images": {"sd": "itv4.png",
                                "hd": "itv4_hd.png",
                                "sd_plus1": "itv4_plus1.png"},
                     "category": "Entertainment",
                     "sequence": 18,
                     "sequence_plus1": 19},
            "ITVBe": {"images": {"sd": "itv_be.png",
                                 "sd_plus1": "itv_be_plus1.png"},
                      "category": "Entertainment",
                      "sequence": 20,
                      "sequence_plus1": 21},
            "Sky Arts": {"images": {"sd": "sky_arts.png",
                                    "hd": "sky_arts_hd.png"},
                         "category": "Entertainment",
                         "sequence": 22},
            "Pick": {"images": {"sd": "pick.png"},
                     "category": "Entertainment",
                     "sequence": 23},
            "W": {"images": {"sd": "w.png",
                             "hd": "w_hd.png",
                             "sd_plus": "w_plus1.png"},
                  "category": "Entertainment",
                  "sequence": 24,
                  "sequence_plus1": 25},
            "Gold": {"images": {"sd": "gold.png",
                                "sd_plus": "gold_plus1.png"},
                     "category": "Entertainment",
                     "sequence": 26,
                     "sequence_plus1": 27},
            "Dave": {"images": {"sd": "dave.png",
                                "hd": "dave_hd.png",
                                "sd_plus1": "dave_ja_vu.png"},
                     "category": "Entertainment",
                     "sequence": 28,
                     "sequence_plus1": 29},
            "Alibi": {"images": {"sd": "alibi.png",
                                 "hd": "alibi_hd.png",
                                 "sd_plus1": "alibi_plus1.png"},
                      "category": "Entertainment",
                      "sequence": 30,
                      "sequence_plus1": 31},
            "Comedy Central": {"images": {"sd": "comedy_central.png",
                                          "hd": "comedy_central_hd.png",
                                          "sd_plus1": "comedy_central_plus1.png"},
                               "category": "Entertainment",
                               "sequence": 32,
                               "sequence_plus1": 33},
            "Comedy Central Extra": {"images": {"sd": "comedy_central_extra.png"},
                                     "category": "Entertainment",
                                     "sequence": 34},
            "MTV": {"images": {"sd": "mtv.png",
                               "hd": "mtv_hd.png"},
                    "category": "Entertainment",
                    "sequence": 35},
            "syfy": {"images": {"sd": "syfy.png",
                                "hd": "syfy_hd.png",
                                "sd_plus1": "syfy_plus1.png"},
                     "category": "Entertainment",
                     "sequence": 36,
                     "sequence_plus1": 37},
            "Universal Channel": {"images": {"sd": "universal.png",
                                             "hd": "universal_hd.png",
                                             "sd_plus1": "universal_plus1.png"},
                                  "category": "Entertainment",
                                  "sequence": 38,
                                  "sequence_plus1": 39},
            "Challenge": {"images": {"sd": "challenge.png",
                                     "sd_plus1": "challenge_plus1.png"},
                          "category": "Entertainment",
                          "sequence": 40,
                          "sequence_plus1": 41},
            "E4": {"images": {"sd": "e4.png",
                              "hd": "e4_hd.png",
                              "sd_plus1": "e4_plus1.png"},
                   "category": "Entertainment",
                   "sequence": 42,
                   "sequence_plus1": 43},
            "More4": {"images": {"sd": "more_4.png",
                                 "hd": "more_4_hd.png",
                                 "sd_plus1": "more_4_plus1.png"},
                      "category": "Entertainment",
                      "sequence": 44,
                      "sequence_plus1": 45},
            "CBS Reality": {"images": {"sd": "cbs_reality.png",
                                       "sd_plus1": "cbs_reality_plus1.png"},
                            "category": "Entertainment",
                            "sequence": 46,
                            "sequence_plus1": 47},
            "Horror Channel": {"images": {"sd": "horror_channel.png",
                                          "sd_plus1": "horror_channel_plus1.png"},
                               "category": "Entertainment",
                               "sequence": 48,
                               "sequence_plus1": 49},
            "5*": {"images": {"sd": "5_star.png",
                              "sd_plus1": "5_star_plus1.png"},
                   "category": "Entertainment",
                   "sequence": 50,
                   "sequence_plus1": 51},
            "5 USA": {"images": {"sd": "5_usa.png",
                                 "sd_plus1": "5_usa_plus1.png"},
                      "category": "Entertainment",
                      "sequence": 52,
                      "sequence_plus1": 53},
            "5 Spike": {"images": {"sd": "5_spike.png"},
                        "category": "Entertainment",
                        "sequence": 54},
            "E! Entertainment": {"images": {"sd": "e_entertainment.png"},
                                 "category": "Entertainment",
                                 "sequence": 55},
            "FOX": {"images": {"sd": "fox.png",
                               "hd": "fox_hd.png",
                               "sd_plus1": "fox_plus1.png"},
                    "category": "Entertainment",
                    "sequence": 56,
                    "sequence_plus1": 57},
            "Made in Leeds": {"images": {"sd": "made_in_leeds.png"},
                              "category": "Entertainment",
                              "sequence": 58},
            "Real Lives": {"images": {"sd": "real_lives.png",
                                      "sd_plus1": "real_lives_plus1.png"},
                           "category": "Entertainment",
                           "sequence": 59,
                           "sequence_plus1": 60},
            "BBC ALBA": {"images": {"sd": "bbc_alba.png"},
                         "category": "Entertainment",
                         "sequence": 61},
            "S4C": {"images": {"sd": "s4c.png"},
                    "category": "Entertainment",
                    "sequence": 62},
            "TLC": {"images": {"sd": "tlc.png",
                               "hd": "tlc_hd.png",
                               "sd_plus1": "tlc_plus1.png"},
                    "category": "Entertainment",
                    "sequence": 63,
                    "sequence_plus1": 64},
            "DMAX": {"images": {"sd": "dmax.png",
                                "sd_plus1": "dmax_plus1.png"},
                     "category": "Entertainment",
                     "sequence": 65,
                     "sequence_plus1": 66},
            "Quest": {"images": {"sd": "quest.png",
                                 "sd_plus1": "quest_plus1.png"},
                      "category": "Entertainment",
                      "sequence": 67,
                      "sequence_plus1": 68},
            "BET": {"images": {"sd": "bet.png"},
                    "category": "Entertainment",
                    "sequence": 69},
            "True Entertainment": {"images": {"sd": "true_entertainment.png"},
                                   "category": "Entertainment",
                                   "sequence": 70},
            "Drama": {"images": {"sd": "drama.png"},
                      "category": "Entertainment",
                      "sequence": 71},
            "CBS Action": {"images": {"sd": "cbs_action.png"},
                           "category": "Entertainment",
                           "sequence": 72},
            "Sony TV": {"images": {"sd": "sony_tv.png"},
                        "category": "Entertainment",
                        "sequence": 73},
            "4Seven": {"images": {"sd": "4seven.png"},
                       "category": "Entertainment",
                       "sequence": 74},
            "CBS Drama": {"images": {"sd": "cbs_drama.png"},
                          "category": "Entertainment",
                          "sequence": 75},
            "TruTV": {"images": {"sd": "tru_tv.png"},
                      "category": "Entertainment",
                      "sequence": 76},
            "Sky Cinema Premiere": {"images": {"sd": "sky_cinema_premiere.png",
                                               "hd": "sky_cinema_premiere_hd.png",
                                               "sd_plus1": "sky_cinema_premiere_plus1.png"},
                                    "category": "Movies",
                                    "sequence": 100,
                                    "sequence_plus1": 101},
            "Sky Cinema Hits": {"images": {"sd": "sky_cinema_hits.png",
                                           "hd": "sky_cinema_hits_hd.png"},
                                "category": "Movies",
                                "sequence": 102},
            "Sky Cinema Greats": {"images": {"sd": "sky_cinema_greats.png",
                                             "hd": "sky_cinema_greats_hd.png"},
                                  "category": "Movies",
                                  "sequence": 103},
            "Sky Cinema Disney": {"images": {"sd": "sky_cinema_disney.png",
                                             "hd": "sky_cinema_disney_hd.png"},
                                  "category": "Movies",
                                  "sequence": 104},
            "Sky Cinema Family": {"images": {"sd": "sky_cinema_drama.png",
                                             "hd": "sky_cinema_drama_hd.png"},
                                  "category": "Movies",
                                  "sequence": 105},
            "Sky Cinema Action": {"images": {"sd": "sky_cinema_action.png",
                                             "hd": "sky_cinema_action_hd.png"},
                                  "category": "Movies",
                                  "sequence": 106},
            "Sky Cinema Comedy": {"images": {"sd": "sky_cinema_comedy.png",
                                             "hd": "sky_cinema_comedy_hd.png"},
                                  "category": "Movies",
                                  "sequence": 107},
            "Sky Cinema Thriller": {"images": {"sd": "sky_cinema_thriller.png",
                                               "hd": "sky_cinema_thriller_hd.png"},
                                    "category": "Movies",
                                    "sequence": 108},
            "Sky Cinema Drama": {"images": {"sd": "sky_cinema_drama.png",
                                            "hd": "sky_cinema_drama_hd.png"},
                                 "category": "Movies",
                                 "sequence": 109},
            "Sky Cinema Sci Fi & Horror": {"images": {"sd": "sky_cinema_scifi.png",
                                                      "hd": "sky_cinema_scifi_hd.png"},
                                           "category": "Movies",
                                           "sequence": 110},
            "Sky Cinema Select": {"images": {"sd": "sky_cinema_select.png",
                                             "hd": "sky_cinema_select_hd.png"},
                                  "category": "Movies",
                                  "sequence": 111},
            "TCM": {"images": {"sd": "tcm.png",
                               "hd": "tcm_hd.png",
                               "sd_plus": "tcm_plus1.png"},
                    "category": "Movies",
                    "sequence": 112,
                    "sequence_plus": 113},
            "Movies 24": {"images": {"sd": "movies_24.png",
                                     "sd_plus": "movies_24_plus1.png"},
                          "category": "Movies",
                          "sequence": 114,
                          "sequence_plus": 115},
            "True Movies": {"images": {"sd": "true_movies.png"},
                            "category": "Movies",
                            "sequence": 116},
            "Sony Movie Channel": {"images": {"sd": "sony_movie_channel.png"},
                                   "category": "Movies",
                                   "sequence": 117},
            "Film4": {"images": {"sd": "film4.png",
                                 "hd": "film4_hd.png",
                                 "sd_plus": "film4_plus1.png"},
                      "category": "Movies",
                      "sequence": 118,
                      "sequence_plus": 119},
            "Sky Sports News": {"images": {"sd": "sky_sports_news.png",
                                           "hd": "sky_sports_news_hd.png"},
                                "category": "Sports",
                                "sequence": 200},
            "Sky Sports Mix": {"images": {"sd": "sky_sports_mix.png",
                                          "hd": "sky_sports_mix_hd.png"},
                               "category": "Sports",
                               "sequence": 201},
            "Sky Sports Main Event": {"images": {"sd": "sky_sports_main_event.png",
                                                 "hd": "sky_sports_main_event_hd.png"},
                                      "category": "Sports",
                                      "sequence": 202},
            "Sky Sports Premier League": {"images": {"sd": "sky_sports_premier_league.png",
                                                     "hd": "sky_sports_premier_league_hd.png"},
                                          "category": "Sports",
                                          "sequence": 203},
            "Sky Sports Football": {"images": {"sd": "sky_sports_football.png",
                                               "hd": "sky_sports_football_hd.png"},
                                    "category": "Sports",
                                    "sequence": 204},
            "Sky Sports Cricket": {"images": {"sd": "sky_sports_cricket.png",
                                              "hd": "sky_sports_cricket_hd.png"},
                                   "category": "Sports",
                                   "sequence": 205},
            "Sky Sports Golf": {"images": {"sd": "sky_sports_golf.png",
                                           "hd": "sky_sports_golf_hd.png"},
                                "category": "Sports",
                                "sequence": 206},
            "Sky Sports F1": {"images": {"sd": "sky_sports_f1.png",
                                         "hd": "sky_sports_f1_hd.png"},
                              "category": "Sports",
                              "sequence": 207},
            "Sky Sports Action": {"images": {"sd": "sky_sports_action.png",
                                             "hd": "sky_sports_action_hd.png"},
                                  "category": "Sports",
                                  "sequence": 208},
            "Sky Sports Arena": {"images": {"sd": "sky_sports_arena.png",
                                            "hd": "sky_sports_arena_hd.png"},
                                 "category": "Sports",
                                 "sequence": 209},
            "At The Races": {"images": {"sd": "at_the_races.png"},
                             "category": "Sports",
                             "sequence": 210},
            "BT Sport 1": {"images": {"sd": "bt_sport_1.png",
                                      "hd": "bt_sport_1_hd.png"},
                           "category": "Sports",
                           "sequence": 211},
            "BT Sport 2": {"images": {"sd": "bt_sport_2.png",
                                      "hd": "bt_sport_2_hd.png"},
                           "category": "Sports",
                           "sequence": 212},
            "BT Sport 3": {"images": {"sd": "bt_sport_3.png",
                                      "hd": "bt_sport_3_hd.png"},
                           "category": "Sports",
                           "sequence": 213},
            "BT Sport ESPN": {"images": {"sd": "bt_sport_espn.png",
                                         "hd": "bt_sport_espn_hd.png"},
                              "category": "Sports",
                              "sequence": 214},
            "Eurosport 1": {"images": {"sd": "eurosport1.png",
                                       "hd": "eurosport1_hd.png"},
                            "category": "Sports",
                            "sequence": 215},
            "Eurosport 2": {"images": {"sd": "eurosport2.png",
                                       "hd": "eurosport2_hd.png"},
                            "category": "Sports",
                            "sequence": 216},
            "Motorsport TV": {"images": {"sd": "motorsport_tv.png"},
                              "category": "Sports",
                              "sequence": 217},
            "FIA Formula E": {"images": {"sd": "fia_formula_e.png"},
                              "category": "Sports",
                              "sequence": 218},
            "BIKE": {"images": {"sd": "bike.png"},
                     "category": "Sports",
                     "sequence": 219},
            "COPA90": {"images": {"sd": "copa90.png"},
                       "category": "Sports",
                       "sequence": 220},
            "Yesterday": {"images": {"sd": "yesterday.png",
                                     "sd_plus1": "yesterday_plus1.png"},
                          "category": "Factual",
                          "sequence": 300,
                          "sequence_plus": 301},
            "Eden": {"images": {"sd": "eden.png",
                                "hd": "eden_hd.png",
                                "sd_plus1": "eden_plus1.png"},
                     "category": "Factual",
                     "sequence": 302,
                     "sequence_plus": 303},
            "Discovery Channel": {"images": {"sd": "discovery_channel.png",
                                             "hd": "discovery_channel_hd.png",
                                             "sd_plus1": "discovery_channel_plus1.png"},
                                  "category": "Factual",
                                  "sequence": 304,
                                  "sequence_plus1": 305},
            "Investigation Discovery": {"images": {"sd": "investigation_discovery.png",
                                                   "sd_plus1": "investigation_discovery_plus1.png"},
                                        "category": "Factual",
                                        "sequence": 306,
                                        "sequence_plus1": 307},
            "Animal Planet": {"images": {"sd": "animal_planet.png",
                                         "hd": "animal_planet_hd.png",
                                         "sd_plus1": "animal_planet_plus1.png"},
                              "category": "Factual",
                              "sequence": 308,
                              "sequence_plus1": 309},
            "Discovery Science": {"images": {"sd": "discovery_science.png",
                                             "sd_plus1": "discovery_science_plus1.png"},
                                  "category": "Factual",
                                  "sequence": 310,
                                  "sequence_plus1": 311},
            "Discovery Turbo": {"images": {"sd": "discovery_turbo.png"},
                                "category": "Factual",
                                "sequence": 312},
            "Discovery History": {"images": {"sd": "discovery_history.png",
                                             "sd_plus1": "discovery_history_plus1.png"},
                                  "category": "Factual",
                                  "sequence": 313,
                                  "sequence_plus1": 314},
            "Nat Geo Wild": {"images": {"sd": "nat_geo_wild.png",
                                        "hd": "nat_geo_wild_hd.png"},
                             "category": "Factual",
                             "sequence": 315},
            "National Geographic": {"images": {"sd": "national_geographic.png",
                                               "hd": "national_geographic_hd.png",
                                               "sd_plus1": "national_geographic_plus1.png"},
                                    "category": "Factual",
                                    "sequence": 316,
                                    "sequence_plus1": 317},
            "Community Channel": {"images": {"sd": "community_channel.png"},
                                  "category": "Factual",
                                  "sequence": 318},
            "History": {"images": {"sd": "history.png",
                                   "sd_plus1": "history_plus1.png"},
                        "category": "Factual",
                        "sequence": 319,
                        "sequence_plus1": 320},
            "H2": {"images": {"sd": "h2.png",
                              "hd": "h2_hd.png"},
                   "category": "Factual",
                   "sequence": 321},
            "Lifetime": {"images": {"sd": "lifetime.png",
                                    "hd": "lifetime_hd.png"},
                         "category": "Factual",
                         "sequence": 322},
            "Crime and Investigation": {"images": {"sd": "crime_and_investigation.png"},
                                        "category": "Factual",
                                        "sequence": 323},
            "PBS America": {"images": {"sd": "pbs_america.png"},
                            "category": "Factual",
                            "sequence": 324},
            "Forces TV": {"images": {"sd": "forces_tv.png"},
                          "category": "Factual",
                          "sequence": 325},
            "Good Food": {"images": {"sd": "good_food.png",
                                     "hd": "good_food_hd.png",
                                     "sd_plus1": "good_food_plus1.png"},
                          "category": "Lifestyle",
                          "sequence": 400,
                          "sequence_plus1": 401},
            "Food Network": {"images": {"sd": "food_network.png"},
                             "category": "Lifestyle",
                             "sequence": 402},
            "Home": {"images": {"sd": "home.png",
                                "sd_plus1": "home_plus1.png"},
                     "category": "Lifestyle",
                     "sequence": 403,
                     "sequence_plus1": 404},
            "Really": {"images": {"sd": "really.png"},
                       "category": "Lifestyle",
                       "sequence": 405},
            "Discovery Home & Health": {"images": {"sd": "discovery_home_and_health.png",
                                                   "sd_plus1": "discovery_home_and_health_plus1.png"},
                                        "category": "Lifestyle",
                                        "sequence": 406,
                                        "sequence_plus1": 407},
            "Discovery Shed": {"images": {"sd": "discovery_shed.png"},
                               "category": "Lifestyle",
                               "sequence": 408},
            "Ginx Esports TV": {"images": {"sd": "ginx.png"},
                                "category": "Lifestyle",
                                "sequence": 409},
            "Travel Channel": {"images": {"sd": "travel_channel.png"},
                               "category": "Lifestyle",
                               "sequence": 410},
            "CBBC": {"images": {"sd": "cbbc.png",
                                "hd": "cbbc_hd.png"},
                     "category": "Kids",
                     "sequence": 500},
            "Cbeebies": {"images": {"sd": "cbeebies.png",
                                    "hd": "cbeebies_hd.png"},
                         "category": "Kids",
                         "sequence": 501},
            "Cartoon Network": {"images": {"sd": "cartoon_network.png",
                                           "hd": "cartoon_network_hd.png",
                                           "sd_plus1": "cartoon_network_plus1.png"},
                                "category": "Kids",
                                "sequence": 502,
                                "sequence_plus1": 503},
            "Cartoonito": {"images": {"sd": "cartoonito.png"},
                           "category": "Kids",
                           "sequence": 504},
            "Disney XD": {"images": {"sd": "disney_xd.png",
                                     "sd_plus1": "disney_xd_plus1.png"},
                          "category": "Kids",
                          "sequence": 505,
                          "sequence_plus1": 506},
            "Nickelodeon": {"images": {"sd": "nickelodeon.png",
                                       "hd": "nickelodeon_hd.png",
                                       "sd_plus1": "nickelodeon_plus1.png"},
                            "category": "Kids",
                            "sequence": 507,
                            "sequence_plus1": 508},
            "Nick Junior": {"images": {"sd": "nick_junior.png"},
                            "category": "Kids",
                            "sequence": 509},
            "Nick Junior Too": {"images": {"sd": "nick_junior_too.png"},
                                "category": "Kids",
                                "sequence": 510},
            "Nick Toons": {"images": {"sd": "nick_toons.png"},
                           "category": "Kids",
                           "sequence": 511},
            "Disney Channel": {"images": {"sd": "disney_channel.png",
                                          "sd_plus1": "disney_channel_plus1.png"},
                               "category": "Kids",
                               "sequence": 512,
                               "sequence_plus1": 513},
            "Disney Junior": {"images": {"sd": "disney_junior.png"},
                              "category": "Kids",
                              "sequence": 514},
            "Boomerang": {"images": {"sd": "boomerang.png",
                                     "sd_plus1": "boomerang_plus1.png"},
                          "category": "Kids",
                          "sequence": 515,
                          "sequence_plus1": 516},
            "CITV": {"images": {"sd": "citv.png"},
                     "category": "Kids",
                     "sequence": 517},
            "Pop": {"images": {"sd": "pop.png"},
                    "category": "Kids",
                    "sequence": 518},
            "Tiny Pop": {"images": {"sd": "tiny_pop.png"},
                         "category": "Kids",
                         "sequence": 519},
            "MTV Music": {"images": {"sd": "mtv_music.png"},
                          "category": "Music",
                          "sequence": 600},
            "MTV Live HD": {"images": {"hd": "mtv_live_hd.png"},
                            "category": "Music",
                            "sequence": 601},
            "MTV Hits": {"images": {"sd": "mtv_hits.png"},
                         "category": "Music",
                         "sequence": 602},
            "MTV Base": {"images": {"sd": "mtv_base.png"},
                         "category": "Music",
                         "sequence": 603},
            "MTV Dance": {"images": {"sd": "mtv_dance.png"},
                          "category": "Music",
                          "sequence": 604},
            "MTV Rocks": {"images": {"sd": "mtv_rocks.png"},
                          "category": "Music",
                          "sequence": 605},
            "VH1": {"images": {"sd": "vh1.png"},
                    "category": "Music",
                    "sequence": 606},
            "Viva": {"images": {"sd": "viva.png"},
                     "category": "Music",
                     "sequence": 607},
            "4 Music": {"images": {"sd": "4music.png"},
                        "category": "Music",
                        "sequence": 608},
            "The Box": {"images": {"sd": "the_box.png"},
                        "category": "Music",
                        "sequence": 609},
            "Kiss": {"images": {"sd": "kiss.png"},
                     "category": "Music",
                     "sequence": 610},
            "Box Hits": {"images": {"sd": "box_hits.png"},
                         "category": "Music",
                         "sequence": 611},
            "Box Upfront": {"images": {"sd": "box_upfront.png"},
                            "category": "Music",
                            "sequence": 612},
            "Magic": {"images": {"sd": "magic.png"},
                      "category": "Music",
                      "sequence": 613},
            "Kerrang! TV": {"images": {"sd": "kerrang.png"},
                            "category": "Music",
                            "sequence": 614},
            "Vintage TV": {"images": {"sd": "vintage_tv.png"},
                           "category": "Music",
                           "sequence": 615},
            "Clubland": {"images": {"sd": "clubland.png"},
                         "category": "Music",
                         "sequence": 616},
            "BBC News": {"images": {"sd": "bbc_news.png",
                                    "hd": "bbc_news_hd.png"},
                         "category": "News",
                         "sequence": 700},
            "Sky News": {"images": {"sd": "sky_news.png",
                                    "hd": "sky_news_hd.png"},
                         "category": "News",
                         "sequence": 701},
            "BBC Parliament": {"images": {"sd": "bbc_parliament.png"},
                               "category": "News",
                               "sequence": 702},
            "CNN": {"images": {"sd": "cnn.png"},
                    "category": "News",
                    "sequence": 703},
            "Bloomberg": {"images": {"sd": "bloomberg.png"},
                          "category": "News",
                          "sequence": 704},
            "CNBC": {"images": {"sd": "cnbc.png"},
                     "category": "News",
                     "sequence": 705},
            "Euronews": {"images": {"sd": "euronews.png"},
                         "category": "News",
                         "sequence": 706},
            "NDTV 24x7": {"images": {"sd": "ndtv_24x7.png"},
                          "category": "News",
                          "sequence": 707},
            "BBC Radio 1": {"images": {"sd": "bbc_radio_1.png"},
                            "category": "Radio",
                            "sequence": 800},
            "BBC Radio 1 Xtra": {"images": {"sd": "bbc_radio_1_xtra.png"},
                                 "category": "Radio",
                                 "sequence": 801},
            "BBC Radio 2": {"images": {"sd": "bbc_radio_2.png"},
                            "category": "Radio",
                            "sequence": 802},
            "BBC Radio 3": {"images": {"sd": "bbc_radio_3.png"},
                            "category": "Radio",
                            "sequence": 803},
            "BBC Radio 4 FM": {"images": {"sd": "bbc_radio_4fm.png"},
                               "category": "Radio",
                               "sequence": 804},
            "BBC Radio 4 Extra": {"images": {"sd": "bbc_radio_4_extra.png"},
                                  "category": "Radio",
                                  "sequence": 805},
            "BBC Radio 4 Long Wave": {"images": {"sd": "bbc_radio_4_long_wave.png"},
                                      "category": "Radio",
                                      "sequence": 806},
            "BBC Radio 5 Live": {"images": {"sd": "bbc_radio_5live.png"},
                                 "category": "Radio",
                                 "sequence": 807},
            "BBC Radio 5 Live Sports Extra": {"images": {"sd": "bbc_radio_5live_sports_extra.png"},
                                              "category": "Radio",
                                              "sequence": 808},
            "BBC Radio 6 Music": {"images": {"sd": "bbc_radio_6music.png"},
                                  "category": "Radio",
                                  "sequence": 809},
            "BBC World Service": {"images": {"sd": "bbc_world_service.png"},
                                  "category": "Radio",
                                  "sequence": 810},
            "Absolute Radio": {"images": {"sd": "absolute_radio.png"},
                               "category": "Radio",
                               "sequence": 811},
            "Smooth Radio": {"images": {"sd": "smooth_radio.png"},
                             "category": "Radio",
                             "sequence": 812},
            "Heart FM": {"images": {"sd": "heart_fm.png"},
                         "category": "Radio",
                         "sequence": 813},
            "LBC": {"images": {"sd": "lbc_radio.png"},
                    "category": "Radio",
                    "sequence": 814},
            "Classic FM": {"images": {"sd": "classic_fm.png"},
                           "category": "Radio",
                           "sequence": 815},
            "Gold Radio": {"images": {"sd": "gold_radio.png"},
                           "category": "Radio",
                           "sequence": 816},
            "Planet Rock": {"images": {"sd": "planet_rock.png"},
                            "category": "Radio",
                            "sequence": 817},
            "Magic Radio": {"images": {"sd": "magic_radio.png"},
                            "category": "Radio",
                            "sequence": 818},
            "Absolute 80s": {"images": {"sd": "absolute_80s.png"},
                             "category": "Radio",
                             "sequence": 819},
            "Absolute Classic Rock": {"images": {"sd": "absolute_classic_rock.png"},
                                      "category": "Radio",
                                      "sequence": 820},
            "Capital FM": {"images": {"sd": "capital_fm.png"},
                           "category": "Radio",
                           "sequence": 821},
            "Capital Xtra": {"images": {"sd": "capital_xtra.png"},
                             "category": "Radio",
                             "sequence": 822},
            "Radio X": {"images": {"sd": "radio_x.png"},
                        "category": "Radio",
                        "sequence": 823},
            "Kiss FM": {"images": {"sd": "kiss_fm.png"},
                        "category": "Radio",
                        "sequence": 824},
            "talkSPORT": {"images": {"sd": "talksport.png"},
                          "category": "Radio",
                          "sequence": 825}
            }
