channels = {"BBC ONE": {"sd": {"image": "bbc_one.png"},
                        "hd": {"image": "bbc_one_hd.png"}},
            "BBC TWO": {"sd": {"image": "bbc_two.png"},
                        "hd": {"image": "bbc_two_hd.png"}},
            "ITV": {"sd": {"image": "itv.png"},
                    "hd": {"image": "itv_hd.png"}},
            "Channel 4": {"sd": {"image": "channel_4.png"},
                          "hd": {"image": "channel_4_hd.png"}},
            "Channel 4 +1": {"sd": {"image": "channel_4_plus1.png"},
                             "hd": False},
            "Channel 5": {"sd": {"image": "channel_5.png"},
                          "hd": {"image": "channel_5_hd.png"}},
            "Channel 5 +1": {"sd": {"image": "channel_5_plus1.png"},
                             "hd": False},
            "My5": {"sd": {"image": "my5.png"},
                    "hd": False},
            "BBC FOUR": {"sd": {"image": "bbc_four.png"},
                         "hd": {"image": "bbc_four_hd.png"}},
            "Sky1": {"sd": {"image": "sky1.png"},
                     "hd": {"image": "sky1_hd.png"}},
            "Sky2": {"sd": {"image": "sky2.png"},
                     "hd": False},
            "Sky Living": {"sd": {"image": "sky_living.png"},
                           "hd": {"image": "sky_living_hd.png"}},
            "Sky Living +1": {"sd": {"image": "sky_living_plus1.png"},
                              "hd": False},
            "ITV +1": {"sd": {"image": "itv_plus1.png"},
                       "hd": False},
            "ITV2": {"sd": {"image": "itv2.png"},
                     "hd": {"image": "itv2_plus1.png"}},
            "ITV2 +1": {"sd": {"image": "itv2_plus1.png"},
                        "hd": False},
            "ITV3": {"sd": {"image": "itv3.png"},
                     "hd": {"image": "itv3_hd.png"}},
            "ITV3 +1": {"sd": {"image": "itv3_plus1.png"},
                        "hd": False},
            "ITV4": {"sd": {"image": "itv4.png"},
                     "hd": {"image": "itv4_hd.png"}},
            "ITV4 +1": {"sd": {"image": "itv4_plus1.png"},
                        "hd": False},
            "ITVBe": {"sd": {"image": "itv_be.png"},
                      "hd": False},
            "ITVBe +1": {"sd": {"image": "itv_be_plus1.png"},
                         "hd": False},
            "Sky Arts": {"sd": {"image": "sky_arts.png"},
                         "hd": {"image": "sky_arts_hd.png"}},
            "Pick": {"sd": {"image": "pick.png"},
                     "hd": False},
            "W": {"sd": {"image": "w.png"},
                  "hd": {"image": "w_hd.png"}},
            "W +1": {"sd": {"image": "w_plus1.png"},
                     "hd": False},
            "Gold": {"sd": {"image": "gold.png"},
                     "hd": False},
            "Gold +1": {"sd": {"image": "gold_plus1.png"},
                        "hd": False},
            "Dave": {"sd": {"image": "dave.png"},
                     "hd": {"image": "dave_hd.png"}},
            "Dave ja vu": {"sd": {"image": "dave_ja_vu.png"},
                           "hd": False},
            "Alibi": {"sd": {"image": "alibi.png"},
                      "hd": {"image": "alibi_hd.png"}},
            "Alibi +1": {"sd": {"image": "alibi_plus1.png"},
                         "hd": False},
            "Comedy Central": {"sd": {"image": "comedy_central.png"},
                               "hd": {"image": "comedy_central_hd.png"}},
            "Comedy Central +1": {"sd": {"image": "comedy_central_plus1.png"},
                                  "hd": False},
            "Comedy Central Extra": {"sd": {"image": "comedy_central_extra.png"},
                                     "hd": False},
            "MTV": {"sd": {"image": "mtv.png"},
                    "hd": {"image": "mtv_hd.png"}},
            "syfy": {"sd": {"image": "syfy.png"},
                     "hd": {"image": "syfy_hd.png"}},
            "syfy +1": {"sd": {"image": "syfy_plus1.png"},
                        "hd": False},
            "Universal Channel": {"sd": {"image": "universal.png"},
                                  "hd": {"image": "universal_hd.png"}},
            "Universal Channel +1": {"sd": {"image": "universal_plus1.png"},
                                     "hd": False},
            "Challenge": {"sd": {"image": "challenge.png"},
                          "hd": False},
            "Challenge +1": {"sd": {"image": "challenge_plus1.png"},
                             "hd": False},
            "E4": {"sd": {"image": "e4.png"},
                   "hd": {"image": "e4_hd.png"}},
            "E4 +1": {"sd": {"image": "e4_plus1.png"},
                      "hd": False},
            "More4": {"sd": {"image": "more_4.png"},
                      "hd": {"image": "more_4_hd.png"}},
            "More4 +1": {"sd": {"image": "more_4_plus1.png"},
                         "hd": False},
            "CBS Reality": {"sd": {"image": "cbs_reality.png"},
                            "hd": False},
            "CBS Reality +1": {"sd": {"image": "cbs_reality_plus1.png"},
                               "hd": False},
            "Horror Channel": {"sd": {"image": "horror_channel.png"},
                               "hd": False},
            "Horror Channel +1": {"sd": {"image": "horror_channel_plus1.png"},
                                  "hd": False},
            "5*": {"sd": {"image": "5_star.png"},
                   "hd": False},
            "5* +1": {"sd": {"image": "5_star_plus1.png"},
                      "hd": False},
            "5 USA": {"sd": {"image": "5_usa.png"},
                      "hd": False},
            "5 USA +1": {"sd": {"image": "5_usa_plus1.png"},
                         "hd": False},
            "5 Spike": {"sd": {"image": "5_spike.png"},
                        "hd": False},
            "E! Entertainment": {"sd": {"image": "e_entertainment.png"},
                                 "hd": False},
            "FOX": {"sd": {"image": "fox.png"},
                    "hd": {"image": "fox_hd.png"}},
            "FOX +1": {"sd": {"image": "fox_plus1.png"},
                       "hd": False},
            "Made in Leeds": {"sd": {"image": "made_in_leeds.png"},
                              "hd": False},
            "Real Lives": {"sd": {"image": "real_lives.png"},
                           "hd": False},
            "Real Lives +1": {"sd": {"image": "real_lives_plus1.png"},
                              "hd": False},
            "BBC ALBA": {"sd": {"image": "bbc_alba.png"},
                         "hd": False},
            "S4C": {"sd": {"image": "s4c.png"},
                    "hd": False},
            "TLC": {"sd": {"image": "tlc.png"},
                    "hd": {"image": "tlc_hd.png"}},
            "TLC +1": {"sd": {"image": "tlc_plus1.png"},
                       "hd": False},
            "DMAX": {"sd": {"image": "dmax.png"},
                     "hd": False},
            "DMAX +1": {"sd": {"image": "dmax_plus1.png"},
                        "hd": False},
            "Quest": {"sd": {"image": "quest.png"},
                      "hd": False},
            "Quest +1": {"sd": {"image": "quest_plus.png"},
                         "hd": False},
            "BET": {"sd": {"image": "bet.png"},
                    "hd": False},
            "True Entertainment": {"sd": {"image": "true_entertainment.png"},
                                   "hd": False},
            "Drama": {"sd": {"image": "drama.png"},
                      "hd": False},
            "CBS Action": {"sd": {"image": "cbs_action.png"},
                           "hd": False},
            "Sony TV": {"sd": {"image": "sony_tv.png"},
                        "hd": False},
            "4Seven": {"sd": {"image": "4seven.png"},
                       "hd": False},
            "CBS Drama": {"sd": {"image": "cbs_drama.png"},
                          "hd": False},
            "TruTV": {"sd": {"image": "tru_tv.png"},
                      "hd": False},
            "Sky Cinema Premiere": {"sd": {"image": "sky_cinema_premiere.png"},
                                    "hd": {"image": "sky_cinema_premiere_hd.png"}},
            "Sky Cinema Premiere +1": {"sd": {"image": "sky_cinema_premiere_plus1.png"},
                                       "hd": False},
            "Sky Cinema Hits": {"sd": {"image": "sky_cinema_hits.png"},
                                "hd": {"image": "sky_cinema_hits_hd.png"}},
            "Sky Cinema Greats": {"sd": {"image": "sky_cinema_greats.png"},
                                  "hd": {"image": "sky_cinema_greats_hd.png"}},
            "Sky Cinema Disney": {"sd": {"image": "sky_cinema_disney.png"},
                                  "hd": {"image": "sky_cinema_disney_hd.png"}},
            "Sky Cinema Family": {"sd": {"image": "sky_cinema_drama.png"},
                                  "hd": {"image": "sky_cinema_drama_hd.png"}},
            "Sky Cinema Action": {"sd": {"image": "sky_cinema_action.png"},
                                  "hd": {"image": "sky_cinema_action_hd.png"}},
            "Sky Cinema Comedy": {"sd": {"image": "sky_cinema_comedy.png"},
                                  "hd": {"image": "sky_cinema_comedy_hd.png"}},
            "Sky Cinema Thriller": {"sd": {"image": "sky_cinema_thriller.png"},
                                    "hd": {"image": "sky_cinema_thriller_hd.png"}},
            "Sky Cinema Drama": {"sd": {"image": "sky_cinema_drama.png"},
                                 "hd": {"image": "sky_cinema_drama_hd.png"}},
            "Sky Cinema Sci Fi & Horror": {"sd": {"image": "sky_cinema_scifi.png"},
                                           "hd": {"image": "sky_cinema_scifi_hd.png"}},
            "Sky Cinema Select": {"sd": {"image": "sky_cinema_select.png"},
                                  "hd": {"image": "sky_cinema_select_hd.png"}},
            "TCM": {"sd": {"image": "tcm.png"},
                    "hd": {"image": "tcm_hd.png"}},
            "TCM +1": {"sd": {"image": "tcm_plus1.png"},
                       "hd": False},
            "Movies 24": {"sd": {"image": "movies_24.png"},
                          "hd": False},
            "Movies 24 +1": {"sd": {"image": "movies_24_plus1.png"},
                          "hd": False},
            "True Movies": {"sd": {"image": "true_movies.png"},
                            "hd": False},
            "Sony Movie Channel": {"sd": {"image": "sony_movie_channel.png"},
                                   "hd": False},
            "Film4": {"sd": {"image": "film4.png"},
                      "hd": {"image": "film4_hd.png"}},
            "Film4 +1": {"sd": {"image": "film4_plus1.png"},
                         "hd": False},
            "Sky Sports News": {"sd": {"image": "sky_sports_news.png"},
                                "hd": {"image": "sky_sports_news_hd.png"}},
            "Sky Sports Mix": {"sd": {"image": "sky_sports_mix.png"},
                               "hd": {"image": "sky_sports_mix_hd.png"}},
            "Sky Sports Main Event": {"sd": {"image": "sky_sports_main_event.png"},
                                      "hd": {"image": "sky_sports_main_event_hd.png"}},
            "Sky Sports Premier League": {"sd": {"image": "sky_sports_premier_league.png"},
                                          "hd": {"image": "sky_sports_premier_league_hd.png"}},
            "Sky Sports Football": {"sd": {"image": "sky_sports_football.png"},
                                    "hd": {"image": "sky_sports_football_hd.png"}},
            "Sky Sports Cricket": {"sd": {"image": "sky_sports_cricket.png"},
                                   "hd": {"image": "sky_sports_cricket_hd.png"}},
            "Sky Sports Golf": {"sd": {"image": "sky_sports_golf.png"},
                                "hd": {"image": "sky_sports_golf_hd.png"}},
            "Sky Sports F1": {"sd": {"image": "sky_sports_f1.png"},
                              "hd": {"image": "sky_sports_f1_hd.png"}},
            "Sky Sports Action": {"sd": {"image": "sky_sports_action.png"},
                                  "hd": {"image": "sky_sports_action_hd.png"}},
            "Sky Sports Arena": {"sd": {"image": "sky_sports_arena.png"},
                                 "hd": {"image": "sky_sports_arena_hd.png"}},
            "At The Races": {"sd": {"image": "at_the_races.png"},
                             "hd": False},
            "BT Sport 1": {"sd": {"image": "bt_sport_1.png"},
                           "hd": {"image": "bt_sport_1_hd.png"}},
            "BT Sport 2": {"sd": {"image": "bt_sport_2.png"},
                           "hd": {"image": "bt_sport_2_hd.png"}},
            "BT Sport 3": {"sd": {"image": "bt_sport_3.png"},
                           "hd": {"image": "bt_sport_3_hd.png"}},
            "BT Sport ESPN": {"sd": {"image": "bt_sport_espn.png"},
                              "hd": {"image": "bt_sport_espn_hd.png"}},
            "Eurosport 1": {"sd": {"image": "eurosport1.png"},
                          "hd": {"image": "eurosport1_hd.png"}},
            "Eurosport 2": {"sd": {"image": "eurosport2.png"},
                            "hd": {"image": "eurosport2_hd.png"}},
            "Motorsport TV": {"sd": {"image": "motorsport_tv_png"},
                              "hd": False},
            "FIA Formula E": {"sd": {"image": "fia_formula_e.png"},
                              "hd": False},
            "BIKE": {"sd": {"image": "bike.png"},
                     "hd": False},
            "COPA90": {"sd": {"image": "copa90.png"},
                       "hd": False},
            "Yesterday": {"sd": {"image": "yesterday.png"},
                          "hd": False},
            "Yesterday +1": {"sd": {"image": "yesterday_plus1.png"},
                             "hd": False},
            "Eden": {"sd": {"image": "eden.png"},
                     "hd": {"image": "eden_hd.png"}},
            "Eden +1": {"sd": {"image": "eden_plus1.png"},
                        "hd": False},
            "Discovery Channel": {"sd": {"image": "discovery_channel.png"},
                                  "hd": {"image": "discovery_channel_hd.png"}},
            "Discovery Channel +1": {"sd": {"image": "discovery_channel_plus1.png"},
                                     "hd": False},
            "Investigation Discovery": {"sd": {"image": "investigation_discovery.png"},
                                        "hd": False},
            "Investigation Discovery +1": {"sd": {"image": "investigation_discovery_plus1.png"},
                                           "hd": False},
            "Animal Planet": {"sd": {"image": "animal_planet.png"},
                              "hd": {"image": "animal_planet_hd.png"}},
            "Animal Planet +1": {"sd": {"image": "animal_planet_plus1.png"},
                                 "hd": False},
            "Discovery Science": {"sd": {"image": "discovery_science.png"},
                                  "hd": False},
            "Discovery Science +1": {"sd": {"image": "discovery_science_plus1.png"},
                                     "hd": False},
            "Discovery Turbo": {"sd": {"image": "discovery_turbo.png"},
                                "hd": False},
            "Discovery History": {"sd": {"image": "discovery_history.png"},
                                  "hd": False},
            "Discovery History +1": {"sd": {"image": "discovery_history_plus1.png"},
                                     "hd": False},
            "Nat Geo Wild": {"sd": {"image": "nat_geo_wild.png"},
                             "hd": {"image": "nat_geo_wild_hd.png"}},
            "National Geographic": {"sd": {"image": "national_geographic.png"},
                                    "hd": {"image": "national_geographic_hd.png"}},
            "National Geographic +1": {"sd": {"image": "national_geographic_plus1.png"},
                                       "hd": False},
            "Community Channel": {"sd": {"image": "community_channel.png"},
                                  "hd": False},
            "History": {"sd": {"image": "history.png"},
                        "hd": False},
            "History +1": {"sd": {"image": "history_plus1.png"},
                           "hd": False},
            "H2": {"sd": {"image": "h2.png"},
                   "hd": {"image": "h2_hd.png"}},
            "Lifetime": {"sd": {"image": "lifetime.png"},
                         "hd": {"image": "lifetime_hd.png"}},
            "Crime and Investigation": {"sd": {"image": "crime_and_investigation.png"},
                                        "hd": False},
            "PBS America": {"sd": {"image": "pbs_america.png"},
                            "hd": False},
            "Forces TV": {"sd": {"image": "forces_tv.png"},
                          "hd": False},
            "Good Food": {"sd": {"image": "good_food.png"},
                          "hd": {"image": "good_food_hd.png"}},
            "Good Food +1": {"sd": {"image": "good_food_plus1.png"},
                             "hd": False},
            "Food Network": {"sd": {"image": "food_network.png"},
                             "hd": False},
            "Home": {"sd": {"image": "home.png"},
                     "hd": False},
            "Home +1": {"sd": {"image": "home_plus1.png"},
                        "hd": False},
            "Really": {"sd": {"image": "really.png"},
                       "hd": False},
            "Discovery Home & Health": {"sd": {"image": "discovery_home_and_health.png"},
                                        "hd": False},
            "Discovery Home & Health +1": {"sd": {"image": "discovery_home_and_health_plus1.png"},
                                           "hd": False},
            "Discovery Shed": {"sd": {"image": "discovery_shed.png"},
                               "hd": False},
            "Ginx Esports TV": {"sd": {"image": "ginx.png"},
                                "hd": False},
            "Travel Channel": {"sd": {"image": "travel_channel.png"},
                               "hd": False},
            "CBBC": {"sd": {"image": "cbbc.png"},
                     "hd": {"image": "cbbc_hd.png"}},
            "Cbeebies": {"sd": {"image": "cbeebies.png"},
                         "hd": {"image": "cbeebies_hd.png"}},
            "Cartoon Network": {"sd": {"image": "cartoon_network.png"},
                                "hd": {"image": "cartoon_network_hd.png"}},
            "Cartoon Network +1": {"sd": {"image": "cartoon_network_plus1.png"},
                                   "hd": False},
            "Cartoonito": {"sd": {"image": "cartoonito.png"},
                           "hd": False},
            "Disney XD": {"sd": {"image": "disney_xd.png"},
                          "hd": False},
            "Disney XD +1": {"sd": {"image": "disney_xd_plus1.png"},
                             "hd": False},
            "Nickelodeon": {"sd": {"image": "nickelodeon.png"},
                            "hd": {"image": "nickelodeon_hd.png"}},
            "Nickelodeon +1": {"sd": {"image": "nickelodeon_plus1.png"},
                               "hd": False},
            "Nick Junior": {"sd": {"image": "nick_junior.png"},
                            "hd": False},
            "Nick Junior Too": {"sd": {"image": "nick_junior_too.png"},
                                "hd": False},
            "Nick Toons": {"sd": {"image": "nick_toons.png"},
                           "hd": False},
            "Disney Channel": {"sd": {"image": "disney_channel.png"},
                               "hd": False},
            "Disney Channel +1": {"sd": {"image": "disney_channel_plus1.png"},
                                  "hd": False},
            "Disney Junior": {"sd": {"image": "disney_junior.png"},
                              "hd": False},
            "Boomerang": {"sd": {"image": "boomerang.png"},
                          "hd": False},
            "Boomerang +1": {"sd": {"image": "boomerang_plus1.png"},
                             "hd": False},
            "CITV": {"sd": {"image": "citv.png"},
                     "hd": False},
            "Pop": {"sd": {"image": "pop.png"},
                    "hd": False},
            "Tiny Pop": {"sd": {"image": "tiny_pop.png"},
                         "hd": False},
            "MTV Music": {"sd": {"image": "mtv_music.png"},
                          "hd": False},
            "MTV Live HD": {"sd": False,
                            "hd": {"image": "mtv_live_hd.png"}},
            "MTV Hits": {"sd": {"image": "mtv_hits.png"},
                         "hd": False},
            "MTV Base": {"sd": {"image": "mtv_base.png"},
                         "hd": False},
            "MTV Dance": {"sd": {"image": "mtv_dance.png"},
                          "hd": False},
            "MTV Rocks": {"sd": {"image": "mtv_rocks.png"},
                          "hd": False},
            "VH1": {"sd": {"image": "vh1.png"},
                    "hd": False},
            "Viva": {"sd": {"image": "viva.png"},
                     "hd": False},
            "4 Music": {"sd": {"image": "4music.png"},
                        "hd": False},
            "The Box": {"sd": {"image": "the_box.png"},
                        "hd": False},
            "Kiss": {"sd": {"image": "kiss.png"},
                     "hd": False},
            "Box Hits": {"sd": {"image": "box_hits.png"},
                         "hd": False},
            "Box Upfront": {"sd": {"image": "box_upfront.png"},
                     "hd": False},
            "Magic": {"sd": {"image": "magic.png"},
                      "hd": False},
            "Kerrang! TV": {"sd": {"image": "kerrang.png"},
                            "hd": False},
            "Vintage TV": {"sd": {"image": "vintage_tv.png"},
                           "hd": False},
            "Clubland": {"sd": {"image": "clubland.png"},
                         "hd": False},
            "BBC News": {"sd": {"image": "bbc_news.png"},
                         "hd": {"image": "bbc_news_hd.png"}},
            "Sky News": {"sd": {"image": "sky_news.png"},
                         "hd": {"image": "sky_news_hd.png"}},
            "BBC Parliament": {"sd": {"image": "bbc_parliament.png"},
                               "hd": False},
            "CNN": {"sd": {"image": "cnn.png"},
                    "hd": False},
            "Bloomberg": {"sd": {"image": "bloomberg.png"},
                          "hd": False},
            "CNBC": {"sd": {"image": "cnbc.png"},
                     "hd": False},
            "Euronews": {"sd": {"image": "euronews.png"},
                         "hd": False},
            "NDTV 24x7": {"sd": {"image": "ndtv_24x7.png"},
                          "hd": False},
            "BBC Radio 1": {"sd": {"image": "bbc_radio_1.png"},
                            "hd": False},
            "BBC Radio 1 Xtra": {"sd": {"image": "bbc_radio_1_xtra.png"},
                                 "hd": False},
            "BBC Radio 2": {"sd": {"image": "bbc_radio_2.png"},
                            "hd": False},
            "BBC Radio 3": {"sd": {"image": "bbc_radio_3.png"},
                            "hd": False},
            "BBC Radio 4 FM": {"sd": {"image": "bbc_radio_4fm.png"},
                               "hd": False},
            "BBC Radio 4 Extra": {"sd": {"image": "bbc_radio_4_extra.png"},
                                  "hd": False},
            "BBC Radio 4 Long Wave": {"sd": {"image": "bbc_radio_4_long_wave.png"},
                                      "hd": False},
            "BBC Radio 5 Live": {"sd": {"image": "bbc_radio_5live.png"},
                                 "hd": False},
            "BBC Radio 5 Live Sports Extra": {"sd": {"image": "bbc_radio_5live_sports_extra.png"},
                                              "hd": False},
            "BBC Radio 6 Music": {"sd": {"image": "bbc_radio_6music.png"},
                                  "hd": False},
            "BBC World Service": {"sd": {"image": "bbc_world_service.png"},
                                  "hd": False},
            "Absolute Radio": {"sd": {"image": "absolute_radio.png"},
                               "hd": False},
            "Smooth Radio": {"sd": {"image": "smooth_radio.png"},
                             "hd": False},
            "Heart FM": {"sd": {"image": "heart_fm.png"},
                         "hd": False},
            "LBC": {"sd": {"image": "lbc_radio.png"},
                    "hd": False},
            "Classic FM": {"sd": {"image": "classic_fm.png"},
                           "hd": False},
            "Gold Radio": {"sd": {"image": "gold_radio.png"},
                           "hd": False},
            "Planet Rock": {"sd": {"image": "planet_rock.png"},
                            "hd": False},
            "Magic Radio": {"sd": {"image": "magic_radio.png"},
                            "hd": False},
            "Absolute 80s": {"sd": {"image": "absolute_80s.png"},
                             "hd": False},
            "Absolute Classic Rock": {"sd": {"image": "absolute_classic_rock.png"},
                                      "hd": False},
            "Capital FM": {"sd": {"image": "capital_fm.png"},
                           "hd": False},
            "Capital Xtra": {"sd": {"image": "capital_xtra.png"},
                             "hd": False},
            "Radio X": {"sd": {"image": "radio_x.png"},
                        "hd": False},
            "Kiss FM": {"sd": {"image": "kiss_fm.png"},
                        "hd": False},
            "talkSPORT": {"sd": {"image": "talksport.png"},
                          "hd": False}
            }