service_variables = {'tv_lg_netcast': {'logo': ['service_logo_lg.png'],
                                       'type': 'service_type_tv.png'},
                     'virginmedia_tivo': {'logo': ['service_logo_virgin.png'],
                                          'type': 'service_type_set-top-box.png'},
                     'xbox_one': {'logo': ['service_logo_xboxone.png'],
                                          'type': 'service_type_gaming.png'},
                     'nest': {'logo': ['service_logo_nest_blue.png'],
                              'type': False},
                     'icloud': {'logo': ['service_logo_apple.png'],
                                'type': False},
                     'news': {'logo': ['service_logo_newsapi.png'],
                              'type': 'service_type_news.png'},
                     'weather': {'logo': ['service_logo_metoffice.jpg', 'service_logo_sunrisesunset.png'],
                                 'type': 'service_type_weather.png'},
                     'tvlistings': {'logo': [],
                                    'type': False}
                     }
